// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind build runner
// To regenerate, run: dart run build_runner build
//
// Generated on: 2025-09-22T17:02:39.106275


import 'package:flutter/material.dart';
import 'package:flywind/tokens/color.dart';

/// Custom colors that provide dot notation access to custom color values
class CustomColors {
  const CustomColors._();

  /// Custom color: test
  static const Color test = Color(0xFFFF0000);
  /// Custom color: test2
  static const Color test2 = Color(0xFF00FF00);

  /// Create default custom colors as FlyColorToken
  static FlyColorToken defaultColors() {
    return FlyColorToken.defaultColor().copyWith(
      extras: {
        'test': Color(0xFFFF0000),
        'test2': Color(0xFF00FF00),
      },
    );
  }
}

/// Extension methods for FlyColorToken to provide dot notation access
extension FlyColorTokenExtensions on FlyColorToken {
  /// Custom color: test
  Color get test => extras['test'] ?? Color(0xFFFF0000);
  /// Custom color: test2
  Color get test2 => extras['test2'] ?? Color(0xFF00FF00);
}
