// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind build runner
// To regenerate, run: dart run build_runner build
//
// Generated on: 2025-09-22T16:42:49.592078


import 'package:flywind/tokens/container.dart';

/// Custom container that provide dot notation access to custom container values
class CustomContainer {
  const CustomContainer._();

  /// Custom container: test
  static const double test = 999.0;

  /// Create default custom container as FlyContainerToken
  static FlyContainerToken defaultContainer() {
    return FlyContainerToken.defaultContainer().copyWith(
      extras: {
        'test': 999.0,
      },
    );
  }
}

/// Extension methods for FlyContainerToken to provide dot notation access
extension FlyContainerTokenExtensions on FlyContainerToken {
  /// Custom container: test
  double get test => extras['test'] ?? 999.0;
}
