// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind build runner
// To regenerate, run: dart run build_runner build
//
// Generated on: 2025-09-22T17:37:50.074373


import 'package:flywind/tokens/breakpoint.dart';

/// Custom breakpoint that provide dot notation access to custom breakpoint values
class CustomBreakpoint {
  const CustomBreakpoint._();

  /// Custom breakpoint: test
  static const double test = 999.0;

  /// Create default custom breakpoint as FlyBreakpointToken
  static FlyBreakpointToken defaultBreakpoint() {
    return FlyBreakpointToken.defaultBreakpoint().copyWith(
      extras: {
        'test': 999.0,
      },
    );
  }
}

/// Extension methods for FlyBreakpointToken to provide dot notation access
extension FlyBreakpointTokenExtensions on FlyBreakpointToken {
  /// Custom breakpoint: test
  double get test => extras['test'] ?? 999.0;
}
