// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind build runner
// To regenerate, run: dart run build_runner build
//
// Generated on: 2025-09-22T17:37:50.076831


import 'package:flywind/tokens/leading.dart';

/// Custom leading that provide dot notation access to custom leading values
class CustomLeading {
  const CustomLeading._();

  /// Custom leading: test
  static const double test = 9.9;

  /// Create default custom leading as FlyLeadingToken
  static FlyLeadingToken defaultLeading() {
    return FlyLeadingToken.defaultLeading().copyWith(
      extras: {
        'test': 9.9,
      },
    );
  }
}

/// Extension methods for FlyLeadingToken to provide dot notation access
extension FlyLeadingTokenExtensions on FlyLeadingToken {
  /// Custom leading: test
  double get test => extras['test'] ?? 9.9;
}
