// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind build runner
// To regenerate, run: dart run build_runner build
//
// Generated on: 2025-09-22T17:37:50.073674


import 'package:flywind/tokens/spacing.dart';

/// Custom spacing that provide dot notation access to custom spacing values
class CustomSpacing {
  const CustomSpacing._();

  /// Custom spacing: test
  static const double test = 99.0;

  /// Create default custom spacing as FlySpacingToken
  static FlySpacingToken defaultSpacing() {
    return FlySpacingToken.defaultSpacing().copyWith(
      extras: {
        'test': 99.0,
      },
    );
  }
}

/// Extension methods for FlySpacingToken to provide dot notation access
extension FlySpacingTokenExtensions on FlySpacingToken {
  /// Custom spacing: test
  double get test => extras['test'] ?? 99.0;
}
