// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind build runner
// To regenerate, run: dart run build_runner build
//
// Generated on: 2025-09-22T17:37:50.074913


import 'package:flywind/tokens/text.dart';

/// Custom text that provide dot notation access to custom text values
class CustomText {
  const CustomText._();

  /// Custom text: test
  static const double test = 99.0;

  /// Create default custom text as FlyTextToken
  static FlyTextToken defaultText() {
    return FlyTextToken.defaultText().copyWith(
      extras: {
        'test': 99.0,
      },
    );
  }
}

/// Extension methods for FlyTextToken to provide dot notation access
extension FlyTextTokenExtensions on FlyTextToken {
  /// Custom text: test
  double get test => extras['test'] ?? 99.0;
}
