// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind build runner
// To regenerate, run: dart run build_runner build
//
// Generated on: 2025-09-22T17:37:50.075954


import 'package:flywind/tokens/tracking.dart';

/// Custom tracking that provide dot notation access to custom tracking values
class CustomTracking {
  const CustomTracking._();

  /// Custom tracking: test
  static const double test = 0.99;

  /// Create default custom tracking as FlyTrackingToken
  static FlyTrackingToken defaultTracking() {
    return FlyTrackingToken.defaultTracking().copyWith(
      extras: {
        'test': 0.99,
      },
    );
  }
}

/// Extension methods for FlyTrackingToken to provide dot notation access
extension FlyTrackingTokenExtensions on FlyTrackingToken {
  /// Custom tracking: test
  double get test => extras['test'] ?? 0.99;
}
