// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by generate_custom.dart
// To regenerate, run: dart generate/generate_custom.dart
//

import 'package:flutter/material.dart';
import '../tokens/color.dart';

/// Custom colors that provide dot notation access to custom color values
class CustomColors {
  const CustomColors._();

  /// Custom color: brand-primary
  static const Color brandPrimary = Color(0xFFFF6B35);
  /// Custom color: brand-secondary
  static const Color brandSecondary = Color(0xFF004E89);
  /// Custom color: brand-accent
  static const Color brandAccent = Color(0xFF00D4AA);
  /// Custom color: semantic-success
  static const Color semanticSuccess = Color(0xFF10B981);
  /// Custom color: semantic-warning
  static const Color semanticWarning = Color(0xFFF59E0B);
  /// Custom color: semantic-error
  static const Color semanticError = Color(0xFFEF4444);
  /// Custom color: semantic-info
  static const Color semanticInfo = Color(0xFF3B82F6);
  /// Custom color: primary
  static const Color primary = Color(0xFF6366F1);
  /// Custom color: secondary
  static const Color secondary = Color(0xFF10B981);
  /// Custom color: accent
  static const Color accent = Color(0xFFF59E0B);
  /// Custom color: text
  static const Color text = Color(0xFF1F2937);
  /// Custom color: text-secondary
  static const Color textSecondary = Color(0xFF6B7280);
  /// Custom color: border
  static const Color border = Color(0xFFE5E7EB);
  /// Custom color: surface
  static const Color surface = Color(0xFFFFFFFF);
  /// Custom color: background
  static const Color background = Color(0xFFF9FAFB);

  /// Create default custom colors as FlyColorToken
  static FlyColorToken defaultColors() {
    return FlyColorToken.defaultColor().copyWith(
      extras: {
        'brand-primary': Color(0xFFFF6B35),
        'brand-secondary': Color(0xFF004E89),
        'brand-accent': Color(0xFF00D4AA),
        'semantic-success': Color(0xFF10B981),
        'semantic-warning': Color(0xFFF59E0B),
        'semantic-error': Color(0xFFEF4444),
        'semantic-info': Color(0xFF3B82F6),
        'primary': Color(0xFF6366F1),
        'secondary': Color(0xFF10B981),
        'accent': Color(0xFFF59E0B),
        'text': Color(0xFF1F2937),
        'text-secondary': Color(0xFF6B7280),
        'border': Color(0xFFE5E7EB),
        'surface': Color(0xFFFFFFFF),
        'background': Color(0xFFF9FAFB),
      },
    );
  }
}

/// Extension methods for FlyColorToken to provide dot notation access
extension FlyColorTokenExtensions on FlyColorToken {
  /// Custom color: brand-primary
  Color get brandPrimary => extras['brand-primary'] ?? Color(0xFFFF6B35);
  /// Custom color: brand-secondary
  Color get brandSecondary => extras['brand-secondary'] ?? Color(0xFF004E89);
  /// Custom color: brand-accent
  Color get brandAccent => extras['brand-accent'] ?? Color(0xFF00D4AA);
  /// Custom color: semantic-success
  Color get semanticSuccess => extras['semantic-success'] ?? Color(0xFF10B981);
  /// Custom color: semantic-warning
  Color get semanticWarning => extras['semantic-warning'] ?? Color(0xFFF59E0B);
  /// Custom color: semantic-error
  Color get semanticError => extras['semantic-error'] ?? Color(0xFFEF4444);
  /// Custom color: semantic-info
  Color get semanticInfo => extras['semantic-info'] ?? Color(0xFF3B82F6);
  /// Custom color: primary
  Color get primary => extras['primary'] ?? Color(0xFF6366F1);
  /// Custom color: secondary
  Color get secondary => extras['secondary'] ?? Color(0xFF10B981);
  /// Custom color: accent
  Color get accent => extras['accent'] ?? Color(0xFFF59E0B);
  /// Custom color: text
  Color get text => extras['text'] ?? Color(0xFF1F2937);
  /// Custom color: text-secondary
  Color get textSecondary => extras['text-secondary'] ?? Color(0xFF6B7280);
  /// Custom color: border
  Color get border => extras['border'] ?? Color(0xFFE5E7EB);
  /// Custom color: surface
  Color get surface => extras['surface'] ?? Color(0xFFFFFFFF);
  /// Custom color: background
  Color get background => extras['background'] ?? Color(0xFFF9FAFB);
}
