// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by generate_custom.dart
// To regenerate, run: dart generate/generate_custom.dart
//

import '../tokens/spacing.dart';

/// Custom spacing that provide dot notation access to custom spacing values
class CustomSpacing {
  const CustomSpacing._();

  /// Custom spacing: xs
  static const double xs = 2.0;
  /// Custom spacing: sm
  static const double sm = 4.0;
  /// Custom spacing: md
  static const double md = 8.0;
  /// Custom spacing: lg
  static const double lg = 16.0;
  /// Custom spacing: xl
  static const double xl = 32.0;
  /// Custom spacing: 2xl
  static const double xl2 = 48.0;
  /// Custom spacing: section
  static const double section = 24.0;
  /// Custom spacing: container
  static const double container = 12.0;

  /// Create default custom spacing as FlySpacingToken
  static FlySpacingToken defaultSpacing() {
    return FlySpacingToken.defaultSpacing().copyWith(
      extras: {
        'xs': 2.0,
        'sm': 4.0,
        'md': 8.0,
        'lg': 16.0,
        'xl': 32.0,
        '2xl': 48.0,
        'section': 24.0,
        'container': 12.0,
      },
    );
  }
}

/// Extension methods for FlySpacingToken to provide dot notation access
extension FlySpacingTokenExtensions on FlySpacingToken {
  /// Custom spacing: xs
  double get xs => extras['xs'] ?? 2.0;
  /// Custom spacing: sm
  double get sm => extras['sm'] ?? 4.0;
  /// Custom spacing: md
  double get md => extras['md'] ?? 8.0;
  /// Custom spacing: lg
  double get lg => extras['lg'] ?? 16.0;
  /// Custom spacing: xl
  double get xl => extras['xl'] ?? 32.0;
  /// Custom spacing: 2xl
  double get xl2 => extras['2xl'] ?? 48.0;
  /// Custom spacing: section
  double get section => extras['section'] ?? 24.0;
  /// Custom spacing: container
  double get container => extras['container'] ?? 12.0;
}
