// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by generate_custom.dart
// To regenerate, run: dart generate/generate_custom.dart
//

import '../tokens/radius.dart';

/// Custom radius that provide dot notation access to custom radius values
class CustomRadius {
  const CustomRadius._();

  /// Custom radius: xs
  static const double xs = 2.0;
  /// Custom radius: sm
  static const double sm = 4.0;
  /// Custom radius: md
  static const double md = 8.0;
  /// Custom radius: lg
  static const double lg = 12.0;
  /// Custom radius: xl
  static const double xl = 16.0;
  /// Custom radius: full
  static const double full = 9999.0;

  /// Create default custom radius as FlyRadiusToken
  static FlyRadiusToken defaultRadius() {
    return FlyRadiusToken.defaultRadius().copyWith(
      extras: {
        'xs': 2.0,
        'sm': 4.0,
        'md': 8.0,
        'lg': 12.0,
        'xl': 16.0,
        'full': 9999.0,
      },
    );
  }
}

/// Extension methods for FlyRadiusToken to provide dot notation access
extension FlyRadiusTokenExtensions on FlyRadiusToken {
  /// Custom radius: xs
  double get xs => extras['xs'] ?? 2.0;
  /// Custom radius: sm
  double get sm => extras['sm'] ?? 4.0;
  /// Custom radius: md
  double get md => extras['md'] ?? 8.0;
  /// Custom radius: lg
  double get lg => extras['lg'] ?? 12.0;
  /// Custom radius: xl
  double get xl => extras['xl'] ?? 16.0;
  /// Custom radius: full
  double get full => extras['full'] ?? 9999.0;
}
