// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by generate_custom.dart
// To regenerate, run: dart generate/generate_custom.dart
//

import '../tokens/text_line_height.dart';

/// Custom text line height that provide dot notation access to custom text line height values
class CustomTextLineHeight {
  const CustomTextLineHeight._();

  /// Custom text line height: test
  static const double test = 99.0;

  /// Create default custom text line height as FlyTextLineHeightToken
  static FlyTextLineHeightToken defaultTextLineHeight() {
    return FlyTextLineHeightToken.defaultTextLineHeight().copyWith(
      extras: {
        'test': 99.0,
      },
    );
  }
}

/// Extension methods for FlyTextLineHeightToken to provide dot notation access
extension FlyTextLineHeightTokenExtensions on FlyTextLineHeightToken {
  /// Custom text line height: test
  double get test => extras['test'] ?? 99.0;
}
