/// Radix color constants generated from P3 color scales
///
/// This file is auto-generated by scripts/generate_radix_colors.dart
/// Do not edit manually. Regenerate when P3 scales are updated.

import 'package:flutter/material.dart';

/// Radix color constants for IDE color previews
///
/// These const Color values enable IDE color previews like Material colors.
class RadixColorConstants {
  RadixColorConstants._();

  static const LightColors light = LightColors();
  static const DarkColors dark = DarkColors();
}

/// Direct const Color properties for IDE autocomplete
/// Usage: RadixColors.blue9, RadixColors.darkGray1, etc.
class RadixColorSteps {
  RadixColorSteps._();

  /// gray step 1 (light mode)
  static const Color gray1 = Color(0xfffcfcfc);

  /// gray step 2 (light mode)
  static const Color gray2 = Color(0xfff9f9f9);

  /// gray step 3 (light mode)
  static const Color gray3 = Color(0xffefefef);

  /// gray step 4 (light mode)
  static const Color gray4 = Color(0xffe8e8e8);

  /// gray step 5 (light mode)
  static const Color gray5 = Color(0xffe0e0e0);

  /// gray step 6 (light mode)
  static const Color gray6 = Color(0xffd8d8d8);

  /// gray step 7 (light mode)
  static const Color gray7 = Color(0xffcecece);

  /// gray step 8 (light mode)
  static const Color gray8 = Color(0xffbbbbbb);

  /// gray step 9 (light mode)
  static const Color gray9 = Color(0xff8d8d8d);

  /// gray step 10 (light mode)
  static const Color gray10 = Color(0xff838383);

  /// gray step 11 (light mode)
  static const Color gray11 = Color(0xff646464);

  /// gray step 12 (light mode)
  static const Color gray12 = Color(0xff202020);

  /// mauve step 1 (light mode)
  static const Color mauve1 = Color(0xfffdfcfd);

  /// mauve step 2 (light mode)
  static const Color mauve2 = Color(0xfffaf9fb);

  /// mauve step 3 (light mode)
  static const Color mauve3 = Color(0xfff1eff3);

  /// mauve step 4 (light mode)
  static const Color mauve4 = Color(0xffe9e7ec);

  /// mauve step 5 (light mode)
  static const Color mauve5 = Color(0xffe2dfe6);

  /// mauve step 6 (light mode)
  static const Color mauve6 = Color(0xffdad8df);

  /// mauve step 7 (light mode)
  static const Color mauve7 = Color(0xffd0cdd6);

  /// mauve step 8 (light mode)
  static const Color mauve8 = Color(0xffbbbac6);

  /// mauve step 9 (light mode)
  static const Color mauve9 = Color(0xff8e8c98);

  /// mauve step 10 (light mode)
  static const Color mauve10 = Color(0xff83828d);

  /// mauve step 11 (light mode)
  static const Color mauve11 = Color(0xff65636c);

  /// mauve step 12 (light mode)
  static const Color mauve12 = Color(0xff211f25);

  /// slate step 1 (light mode)
  static const Color slate1 = Color(0xfffcfcfd);

  /// slate step 2 (light mode)
  static const Color slate2 = Color(0xfff9f9fb);

  /// slate step 3 (light mode)
  static const Color slate3 = Color(0xfff0f0f3);

  /// slate step 4 (light mode)
  static const Color slate4 = Color(0xffe8e8ec);

  /// slate step 5 (light mode)
  static const Color slate5 = Color(0xffe0e1e6);

  /// slate step 6 (light mode)
  static const Color slate6 = Color(0xffd9d9df);

  /// slate step 7 (light mode)
  static const Color slate7 = Color(0xffcdced6);

  /// slate step 8 (light mode)
  static const Color slate8 = Color(0xffb9bbc5);

  /// slate step 9 (light mode)
  static const Color slate9 = Color(0xff8b8d97);

  /// slate step 10 (light mode)
  static const Color slate10 = Color(0xff80838c);

  /// slate step 11 (light mode)
  static const Color slate11 = Color(0xff61646b);

  /// slate step 12 (light mode)
  static const Color slate12 = Color(0xff1d2024);

  /// sage step 1 (light mode)
  static const Color sage1 = Color(0xfffbfdfc);

  /// sage step 2 (light mode)
  static const Color sage2 = Color(0xfff7f9f8);

  /// sage step 3 (light mode)
  static const Color sage3 = Color(0xffeef1f0);

  /// sage step 4 (light mode)
  static const Color sage4 = Color(0xffe7e9e8);

  /// sage step 5 (light mode)
  static const Color sage5 = Color(0xffdfe2e0);

  /// sage step 6 (light mode)
  static const Color sage6 = Color(0xffd7dad8);

  /// sage step 7 (light mode)
  static const Color sage7 = Color(0xffcccfce);

  /// sage step 8 (light mode)
  static const Color sage8 = Color(0xffb9bcbb);

  /// sage step 9 (light mode)
  static const Color sage9 = Color(0xff878e8b);

  /// sage step 10 (light mode)
  static const Color sage10 = Color(0xff7d8381);

  /// sage step 11 (light mode)
  static const Color sage11 = Color(0xff606563);

  /// sage step 12 (light mode)
  static const Color sage12 = Color(0xff1b211e);

  /// olive step 1 (light mode)
  static const Color olive1 = Color(0xfffcfdfc);

  /// olive step 2 (light mode)
  static const Color olive2 = Color(0xfff8faf8);

  /// olive step 3 (light mode)
  static const Color olive3 = Color(0xffeff1ef);

  /// olive step 4 (light mode)
  static const Color olive4 = Color(0xffe7e9e7);

  /// olive step 5 (light mode)
  static const Color olive5 = Color(0xffe0e2df);

  /// olive step 6 (light mode)
  static const Color olive6 = Color(0xffd8dad7);

  /// olive step 7 (light mode)
  static const Color olive7 = Color(0xffcdcfcc);

  /// olive step 8 (light mode)
  static const Color olive8 = Color(0xffb9bcb8);

  /// olive step 9 (light mode)
  static const Color olive9 = Color(0xff8a8e88);

  /// olive step 10 (light mode)
  static const Color olive10 = Color(0xff80837d);

  /// olive step 11 (light mode)
  static const Color olive11 = Color(0xff61655f);

  /// olive step 12 (light mode)
  static const Color olive12 = Color(0xff1e211c);

  /// sand step 1 (light mode)
  static const Color sand1 = Color(0xfffdfdfc);

  /// sand step 2 (light mode)
  static const Color sand2 = Color(0xfff9f9f8);

  /// sand step 3 (light mode)
  static const Color sand3 = Color(0xfff0f0ef);

  /// sand step 4 (light mode)
  static const Color sand4 = Color(0xffe9e9e6);

  /// sand step 5 (light mode)
  static const Color sand5 = Color(0xffe2e1df);

  /// sand step 6 (light mode)
  static const Color sand6 = Color(0xffdad9d6);

  /// sand step 7 (light mode)
  static const Color sand7 = Color(0xffcfcfca);

  /// sand step 8 (light mode)
  static const Color sand8 = Color(0xffbcbbb6);

  /// sand step 9 (light mode)
  static const Color sand9 = Color(0xff8d8d87);

  /// sand step 10 (light mode)
  static const Color sand10 = Color(0xff82827c);

  /// sand step 11 (light mode)
  static const Color sand11 = Color(0xff63635e);

  /// sand step 12 (light mode)
  static const Color sand12 = Color(0xff21201c);

  /// tomato step 1 (light mode)
  static const Color tomato1 = Color(0xfffefcfc);

  /// tomato step 2 (light mode)
  static const Color tomato2 = Color(0xfffdf8f7);

  /// tomato step 3 (light mode)
  static const Color tomato3 = Color(0xfffbece8);

  /// tomato step 4 (light mode)
  static const Color tomato4 = Color(0xfffeddd5);

  /// tomato step 5 (light mode)
  static const Color tomato5 = Color(0xfffacfc4);

  /// tomato step 6 (light mode)
  static const Color tomato6 = Color(0xfff3bfb2);

  /// tomato step 7 (light mode)
  static const Color tomato7 = Color(0xffeaac9c);

  /// tomato step 8 (light mode)
  static const Color tomato8 = Color(0xffdf9380);

  /// tomato step 9 (light mode)
  static const Color tomato9 = Color(0xffd4583b);

  /// tomato step 10 (light mode)
  static const Color tomato10 = Color(0xffcd5033);

  /// tomato step 11 (light mode)
  static const Color tomato11 = Color(0xffc14227);

  /// tomato step 12 (light mode)
  static const Color tomato12 = Color(0xff552a22);

  /// red step 1 (light mode)
  static const Color red1 = Color(0xfffefcfc);

  /// red step 2 (light mode)
  static const Color red2 = Color(0xfffef8f8);

  /// red step 3 (light mode)
  static const Color red3 = Color(0xfffbecec);

  /// red step 4 (light mode)
  static const Color red4 = Color(0xffffdddd);

  /// red step 5 (light mode)
  static const Color red5 = Color(0xfffbcfcf);

  /// red step 6 (light mode)
  static const Color red6 = Color(0xfff4c0bf);

  /// red step 7 (light mode)
  static const Color red7 = Color(0xffe9acab);

  /// red step 8 (light mode)
  static const Color red8 = Color(0xffde9392);

  /// red step 9 (light mode)
  static const Color red9 = Color(0xffd45453);

  /// red step 10 (light mode)
  static const Color red10 = Color(0xffcb4b49);

  /// red step 11 (light mode)
  static const Color red11 = Color(0xffbe3c39);

  /// red step 12 (light mode)
  static const Color red12 = Color(0xff5c1d24);

  /// ruby step 1 (light mode)
  static const Color ruby1 = Color(0xfffefcfd);

  /// ruby step 2 (light mode)
  static const Color ruby2 = Color(0xfffef8f8);

  /// ruby step 3 (light mode)
  static const Color ruby3 = Color(0xfffbebed);

  /// ruby step 4 (light mode)
  static const Color ruby4 = Color(0xfffcdee2);

  /// ruby step 5 (light mode)
  static const Color ruby5 = Color(0xfff7d0d6);

  /// ruby step 6 (light mode)
  static const Color ruby6 = Color(0xffefc1c8);

  /// ruby step 7 (light mode)
  static const Color ruby7 = Color(0xffe5afb8);

  /// ruby step 8 (light mode)
  static const Color ruby8 = Color(0xffd996a3);

  /// ruby step 9 (light mode)
  static const Color ruby9 = Color(0xffd45268);

  /// ruby step 10 (light mode)
  static const Color ruby10 = Color(0xffcb4960);

  /// ruby step 11 (light mode)
  static const Color ruby11 = Color(0xffba364f);

  /// ruby step 12 (light mode)
  static const Color ruby12 = Color(0xff5c1d2c);

  /// crimson step 1 (light mode)
  static const Color crimson1 = Color(0xfffefcfd);

  /// crimson step 2 (light mode)
  static const Color crimson2 = Color(0xfffdf7f9);

  /// crimson step 3 (light mode)
  static const Color crimson3 = Color(0xfffceaf0);

  /// crimson step 4 (light mode)
  static const Color crimson4 = Color(0xfff9dde7);

  /// crimson step 5 (light mode)
  static const Color crimson5 = Color(0xfff3cfdc);

  /// crimson step 6 (light mode)
  static const Color crimson6 = Color(0xffebc1d0);

  /// crimson step 7 (light mode)
  static const Color crimson7 = Color(0xffe0aec2);

  /// crimson step 8 (light mode)
  static const Color crimson8 = Color(0xffd597b1);

  /// crimson step 9 (light mode)
  static const Color crimson9 = Color(0xffd74c81);

  /// crimson step 10 (light mode)
  static const Color crimson10 = Color(0xffce4477);

  /// crimson step 11 (light mode)
  static const Color crimson11 = Color(0xffba3263);

  /// crimson step 12 (light mode)
  static const Color crimson12 = Color(0xff5a1c38);

  /// pink step 1 (light mode)
  static const Color pink1 = Color(0xfffefcfe);

  /// pink step 2 (light mode)
  static const Color pink2 = Color(0xfffdf7fb);

  /// pink step 3 (light mode)
  static const Color pink3 = Color(0xfffaeaf5);

  /// pink step 4 (light mode)
  static const Color pink4 = Color(0xfff6ddee);

  /// pink step 5 (light mode)
  static const Color pink5 = Color(0xffefd0e5);

  /// pink step 6 (light mode)
  static const Color pink6 = Color(0xffe7c1db);

  /// pink step 7 (light mode)
  static const Color pink7 = Color(0xffdeaecf);

  /// pink step 8 (light mode)
  static const Color pink8 = Color(0xffd296c0);

  /// pink step 9 (light mode)
  static const Color pink9 = Color(0xffc64c9c);

  /// pink step 10 (light mode)
  static const Color pink10 = Color(0xffbf4594);

  /// pink step 11 (light mode)
  static const Color pink11 = Color(0xffb23887);

  /// pink step 12 (light mode)
  static const Color pink12 = Color(0xff5d1a47);

  /// plum step 1 (light mode)
  static const Color plum1 = Color(0xfffefcff);

  /// plum step 2 (light mode)
  static const Color plum2 = Color(0xfffcf8fc);

  /// plum step 3 (light mode)
  static const Color plum3 = Color(0xfff8ebfa);

  /// plum step 4 (light mode)
  static const Color plum4 = Color(0xfff3dff6);

  /// plum step 5 (light mode)
  static const Color plum5 = Color(0xffecd2f1);

  /// plum step 6 (light mode)
  static const Color plum6 = Color(0xffe3c3ea);

  /// plum step 7 (light mode)
  static const Color plum7 = Color(0xffd6afe0);

  /// plum step 8 (light mode)
  static const Color plum8 = Color(0xffc694d4);

  /// plum step 9 (light mode)
  static const Color plum9 = Color(0xff9f50b5);

  /// plum step 10 (light mode)
  static const Color plum10 = Color(0xff964aaa);

  /// plum step 11 (light mode)
  static const Color plum11 = Color(0xff8a439e);

  /// plum step 12 (light mode)
  static const Color plum12 = Color(0xff4c1d5a);

  /// purple step 1 (light mode)
  static const Color purple1 = Color(0xfffefcfe);

  /// purple step 2 (light mode)
  static const Color purple2 = Color(0xfffbf8fd);

  /// purple step 3 (light mode)
  static const Color purple3 = Color(0xfff6edfc);

  /// purple step 4 (light mode)
  static const Color purple4 = Color(0xffefe2fa);

  /// purple step 5 (light mode)
  static const Color purple5 = Color(0xffe7d5f6);

  /// purple step 6 (light mode)
  static const Color purple6 = Color(0xffdbc5f0);

  /// purple step 7 (light mode)
  static const Color purple7 = Color(0xffccb0e8);

  /// purple step 8 (light mode)
  static const Color purple8 = Color(0xffb795df);

  /// purple step 9 (light mode)
  static const Color purple9 = Color(0xff8551c0);

  /// purple step 10 (light mode)
  static const Color purple10 = Color(0xff7b4ab3);

  /// purple step 11 (light mode)
  static const Color purple11 = Color(0xff7948af);

  /// purple step 12 (light mode)
  static const Color purple12 = Color(0xff3c225d);

  /// violet step 1 (light mode)
  static const Color violet1 = Color(0xfffdfcfe);

  /// violet step 2 (light mode)
  static const Color violet2 = Color(0xfff9f8fe);

  /// violet step 3 (light mode)
  static const Color violet3 = Color(0xfff3f0fd);

  /// violet step 4 (light mode)
  static const Color violet4 = Color(0xffeae5ff);

  /// violet step 5 (light mode)
  static const Color violet5 = Color(0xffdfd9ff);

  /// violet step 6 (light mode)
  static const Color violet6 = Color(0xffd2cafa);

  /// violet step 7 (light mode)
  static const Color violet7 = Color(0xffc0b6f0);

  /// violet step 8 (light mode)
  static const Color violet8 = Color(0xffa79ae6);

  /// violet step 9 (light mode)
  static const Color violet9 = Color(0xff6a57c8);

  /// violet step 10 (light mode)
  static const Color violet10 = Color(0xff614ebd);

  /// violet step 11 (light mode)
  static const Color violet11 = Color(0xff6251b3);

  /// violet step 12 (light mode)
  static const Color violet12 = Color(0xff2e265c);

  /// iris step 1 (light mode)
  static const Color iris1 = Color(0xfffdfdff);

  /// iris step 2 (light mode)
  static const Color iris2 = Color(0xfff8f8fe);

  /// iris step 3 (light mode)
  static const Color iris3 = Color(0xfff0f1fd);

  /// iris step 4 (light mode)
  static const Color iris4 = Color(0xffe6e7ff);

  /// iris step 5 (light mode)
  static const Color iris5 = Color(0xffdbdcff);

  /// iris step 6 (light mode)
  static const Color iris6 = Color(0xffcccdfc);

  /// iris step 7 (light mode)
  static const Color iris7 = Color(0xffb8b9f4);

  /// iris step 8 (light mode)
  static const Color iris8 = Color(0xff9c9eea);

  /// iris step 9 (light mode)
  static const Color iris9 = Color(0xff5b5bcf);

  /// iris step 10 (light mode)
  static const Color iris10 = Color(0xff5151c5);

  /// iris step 11 (light mode)
  static const Color iris11 = Color(0xff5653bf);

  /// iris step 12 (light mode)
  static const Color iris12 = Color(0xff27295f);

  /// indigo step 1 (light mode)
  static const Color indigo1 = Color(0xfffdfdfe);

  /// indigo step 2 (light mode)
  static const Color indigo2 = Color(0xfff8f9fe);

  /// indigo step 3 (light mode)
  static const Color indigo3 = Color(0xffeef2fd);

  /// indigo step 4 (light mode)
  static const Color indigo4 = Color(0xffe2e9ff);

  /// indigo step 5 (light mode)
  static const Color indigo5 = Color(0xffd4deff);

  /// indigo step 6 (light mode)
  static const Color indigo6 = Color(0xffc4d0fe);

  /// indigo step 7 (light mode)
  static const Color indigo7 = Color(0xffafbdf4);

  /// indigo step 8 (light mode)
  static const Color indigo8 = Color(0xff91a3ea);

  /// indigo step 9 (light mode)
  static const Color indigo9 = Color(0xff4662d5);

  /// indigo step 10 (light mode)
  static const Color indigo10 = Color(0xff3c57cc);

  /// indigo step 11 (light mode)
  static const Color indigo11 = Color(0xff415ac1);

  /// indigo step 12 (light mode)
  static const Color indigo12 = Color(0xff222d59);

  /// blue step 1 (light mode)
  static const Color blue1 = Color(0xfffbfdff);

  /// blue step 2 (light mode)
  static const Color blue2 = Color(0xfff5fafe);

  /// blue step 3 (light mode)
  static const Color blue3 = Color(0xffe9f4fd);

  /// blue step 4 (light mode)
  static const Color blue4 = Color(0xffdaeeff);

  /// blue step 5 (light mode)
  static const Color blue5 = Color(0xffc9e4fe);

  /// blue step 6 (light mode)
  static const Color blue6 = Color(0xffb5d7f9);

  /// blue step 7 (light mode)
  static const Color blue7 = Color(0xff9bc6f1);

  /// blue step 8 (light mode)
  static const Color blue8 = Color(0xff73afea);

  /// blue step 9 (light mode)
  static const Color blue9 = Color(0xff3f8ef7);

  /// blue step 10 (light mode)
  static const Color blue10 = Color(0xff3c85e9);

  /// blue step 11 (light mode)
  static const Color blue11 = Color(0xff2670d6);

  /// blue step 12 (light mode)
  static const Color blue12 = Color(0xff1a3161);

  /// cyan step 1 (light mode)
  static const Color cyan1 = Color(0xfffafdfe);

  /// cyan step 2 (light mode)
  static const Color cyan2 = Color(0xfff4fafb);

  /// cyan step 3 (light mode)
  static const Color cyan3 = Color(0xffe2f6f9);

  /// cyan step 4 (light mode)
  static const Color cyan4 = Color(0xffd1f0f5);

  /// cyan step 5 (light mode)
  static const Color cyan5 = Color(0xffc0e7ee);

  /// cyan step 6 (light mode)
  static const Color cyan6 = Color(0xffabdce6);

  /// cyan step 7 (light mode)
  static const Color cyan7 = Color(0xff90ccda);

  /// cyan step 8 (light mode)
  static const Color cyan8 = Color(0xff63b6cb);

  /// cyan step 9 (light mode)
  static const Color cyan9 = Color(0xff48a0c3);

  /// cyan step 10 (light mode)
  static const Color cyan10 = Color(0xff4395b5);

  /// cyan step 11 (light mode)
  static const Color cyan11 = Color(0xff147aa1);

  /// cyan step 12 (light mode)
  static const Color cyan12 = Color(0xff1c3b47);

  /// teal step 1 (light mode)
  static const Color teal1 = Color(0xfffbfefd);

  /// teal step 2 (light mode)
  static const Color teal2 = Color(0xfff4fbf9);

  /// teal step 3 (light mode)
  static const Color teal3 = Color(0xffe4f8f3);

  /// teal step 4 (light mode)
  static const Color teal4 = Color(0xffd4f2eb);

  /// teal step 5 (light mode)
  static const Color teal5 = Color(0xffc2e9e0);

  /// teal step 6 (light mode)
  static const Color teal6 = Color(0xffaedcd2);

  /// teal step 7 (light mode)
  static const Color teal7 = Color(0xff94cbc1);

  /// teal step 8 (light mode)
  static const Color teal8 = Color(0xff6eb7ab);

  /// teal step 9 (light mode)
  static const Color teal9 = Color(0xff4ca294);

  /// teal step 10 (light mode)
  static const Color teal10 = Color(0xff46998a);

  /// teal step 11 (light mode)
  static const Color teal11 = Color(0xff14806e);

  /// teal step 12 (light mode)
  static const Color teal12 = Color(0xff1c3c38);

  /// jade step 1 (light mode)
  static const Color jade1 = Color(0xfffbfefd);

  /// jade step 2 (light mode)
  static const Color jade2 = Color(0xfff5fbf7);

  /// jade step 3 (light mode)
  static const Color jade3 = Color(0xffe9f6ee);

  /// jade step 4 (light mode)
  static const Color jade4 = Color(0xffdbf0e4);

  /// jade step 5 (light mode)
  static const Color jade5 = Color(0xffcbe8d8);

  /// jade step 6 (light mode)
  static const Color jade6 = Color(0xffb6dcca);

  /// jade step 7 (light mode)
  static const Color jade7 = Color(0xff9acdb7);

  /// jade step 8 (light mode)
  static const Color jade8 = Color(0xff70b8a0);

  /// jade step 9 (light mode)
  static const Color jade9 = Color(0xff51a185);

  /// jade step 10 (light mode)
  static const Color jade10 = Color(0xff4c977c);

  /// jade step 11 (light mode)
  static const Color jade11 = Color(0xff26805e);

  /// jade step 12 (light mode)
  static const Color jade12 = Color(0xff243a31);

  /// green step 1 (light mode)
  static const Color green1 = Color(0xfffbfefc);

  /// green step 2 (light mode)
  static const Color green2 = Color(0xfff6fbf7);

  /// green step 3 (light mode)
  static const Color green3 = Color(0xffe9f6ec);

  /// green step 4 (light mode)
  static const Color green4 = Color(0xffdbf0e0);

  /// green step 5 (light mode)
  static const Color green5 = Color(0xffcbe7d3);

  /// green step 6 (light mode)
  static const Color green6 = Color(0xffb7dcc2);

  /// green step 7 (light mode)
  static const Color green7 = Color(0xff9cccac);

  /// green step 8 (light mode)
  static const Color green8 = Color(0xff73b68f);

  /// green step 9 (light mode)
  static const Color green9 = Color(0xff55a271);

  /// green step 10 (light mode)
  static const Color green10 = Color(0xff4f986a);

  /// green step 11 (light mode)
  static const Color green11 = Color(0xff308052);

  /// green step 12 (light mode)
  static const Color green12 = Color(0xff223a2e);

  /// grass step 1 (light mode)
  static const Color grass1 = Color(0xfffbfefb);

  /// grass step 2 (light mode)
  static const Color grass2 = Color(0xfff6fbf6);

  /// grass step 3 (light mode)
  static const Color grass3 = Color(0xffebf6ea);

  /// grass step 4 (light mode)
  static const Color grass4 = Color(0xffdef0dd);

  /// grass step 5 (light mode)
  static const Color grass5 = Color(0xffcfe8cd);

  /// grass step 6 (light mode)
  static const Color grass6 = Color(0xffbbdcb9);

  /// grass step 7 (light mode)
  static const Color grass7 = Color(0xffa0cd9f);

  /// grass step 8 (light mode)
  static const Color grass8 = Color(0xff7ab87b);

  /// grass step 9 (light mode)
  static const Color grass9 = Color(0xff61a560);

  /// grass step 10 (light mode)
  static const Color grass10 = Color(0xff589857);

  /// grass step 11 (light mode)
  static const Color grass11 = Color(0xff437c43);

  /// grass step 12 (light mode)
  static const Color grass12 = Color(0xff273b27);

  /// brown step 1 (light mode)
  static const Color brown1 = Color(0xfffefdfc);

  /// brown step 2 (light mode)
  static const Color brown2 = Color(0xfffcf9f6);

  /// brown step 3 (light mode)
  static const Color brown3 = Color(0xfff5efe8);

  /// brown step 4 (light mode)
  static const Color brown4 = Color(0xffeee5da);

  /// brown step 5 (light mode)
  static const Color brown5 = Color(0xffe8dacb);

  /// brown step 6 (light mode)
  static const Color brown6 = Color(0xffe0ceba);

  /// brown step 7 (light mode)
  static const Color brown7 = Color(0xffd6bda3);

  /// brown step 8 (light mode)
  static const Color brown8 = Color(0xffc7a583);

  /// brown step 9 (light mode)
  static const Color brown9 = Color(0xffa6815e);

  /// brown step 10 (light mode)
  static const Color brown10 = Color(0xff997758);

  /// brown step 11 (light mode)
  static const Color brown11 = Color(0xff7c5f49);

  /// brown step 12 (light mode)
  static const Color brown12 = Color(0xff3c342f);

  /// orange step 1 (light mode)
  static const Color orange1 = Color(0xfffefcfb);

  /// orange step 2 (light mode)
  static const Color orange2 = Color(0xfffdf7ee);

  /// orange step 3 (light mode)
  static const Color orange3 = Color(0xfffcefd9);

  /// orange step 4 (light mode)
  static const Color orange4 = Color(0xffffdfaf);

  /// orange step 5 (light mode)
  static const Color orange5 = Color(0xffffd195);

  /// orange step 6 (light mode)
  static const Color orange6 = Color(0xfff9c48b);

  /// orange step 7 (light mode)
  static const Color orange7 = Color(0xffeab17c);

  /// orange step 8 (light mode)
  static const Color orange8 = Color(0xffe09861);

  /// orange step 9 (light mode)
  static const Color orange9 = Color(0xffe67333);

  /// orange step 10 (light mode)
  static const Color orange10 = Color(0xffde682a);

  /// orange step 11 (light mode)
  static const Color orange11 = Color(0xffc25700);

  /// orange step 12 (light mode)
  static const Color orange12 = Color(0xff522f20);

  /// sky step 1 (light mode)
  static const Color sky1 = Color(0xfffafeff);

  /// sky step 2 (light mode)
  static const Color sky2 = Color(0xfff3fafc);

  /// sky step 3 (light mode)
  static const Color sky3 = Color(0xffe5f6fc);

  /// sky step 4 (light mode)
  static const Color sky4 = Color(0xffd7eff9);

  /// sky step 5 (light mode)
  static const Color sky5 = Color(0xffc6e6f3);

  /// sky step 6 (light mode)
  static const Color sky6 = Color(0xffb3d9eb);

  /// sky step 7 (light mode)
  static const Color sky7 = Color(0xff9ac8e0);

  /// sky step 8 (light mode)
  static const Color sky8 = Color(0xff75b1d3);

  /// sky step 9 (light mode)
  static const Color sky9 = Color(0xff95e0fb);

  /// sky step 10 (light mode)
  static const Color sky10 = Color(0xff8ed7f5);

  /// sky step 11 (light mode)
  static const Color sky11 = Color(0xff31729a);

  /// sky step 12 (light mode)
  static const Color sky12 = Color(0xff253d54);

  /// mint step 1 (light mode)
  static const Color mint1 = Color(0xfffafefd);

  /// mint step 2 (light mode)
  static const Color mint2 = Color(0xfff4fbf9);

  /// mint step 3 (light mode)
  static const Color mint3 = Color(0xffe2f8f2);

  /// mint step 4 (light mode)
  static const Color mint4 = Color(0xffd1f3ea);

  /// mint step 5 (light mode)
  static const Color mint5 = Color(0xffbeeadf);

  /// mint step 6 (light mode)
  static const Color mint6 = Color(0xffaaded1);

  /// mint step 7 (light mode)
  static const Color mint7 = Color(0xff91cdbe);

  /// mint step 8 (light mode)
  static const Color mint8 = Color(0xff6bb9a5);

  /// mint step 9 (light mode)
  static const Color mint9 = Color(0xff9ee8d5);

  /// mint step 10 (light mode)
  static const Color mint10 = Color(0xff95decb);

  /// mint step 11 (light mode)
  static const Color mint11 = Color(0xff347665);

  /// mint step 12 (light mode)
  static const Color mint12 = Color(0xff23423c);

  /// lime step 1 (light mode)
  static const Color lime1 = Color(0xfffcfdfa);

  /// lime step 2 (light mode)
  static const Color lime2 = Color(0xfff9faf3);

  /// lime step 3 (light mode)
  static const Color lime3 = Color(0xffeff6d9);

  /// lime step 4 (light mode)
  static const Color lime4 = Color(0xffe4f0c2);

  /// lime step 5 (light mode)
  static const Color lime5 = Color(0xffd7e6ad);

  /// lime step 6 (light mode)
  static const Color lime6 = Color(0xffc6d999);

  /// lime step 7 (light mode)
  static const Color lime7 = Color(0xffb1c882);

  /// lime step 8 (light mode)
  static const Color lime8 = Color(0xff95b460);

  /// lime step 9 (light mode)
  static const Color lime9 = Color(0xffc7ed77);

  /// lime step 10 (light mode)
  static const Color lime10 = Color(0xffbbe465);

  /// lime step 11 (light mode)
  static const Color lime11 = Color(0xff627b3a);

  /// lime step 12 (light mode)
  static const Color lime12 = Color(0xff394021);

  /// yellow step 1 (light mode)
  static const Color yellow1 = Color(0xfffdfdf9);

  /// yellow step 2 (light mode)
  static const Color yellow2 = Color(0xfffefceb);

  /// yellow step 3 (light mode)
  static const Color yellow3 = Color(0xfffefabf);

  /// yellow step 4 (light mode)
  static const Color yellow4 = Color(0xfffdf3a0);

  /// yellow step 5 (light mode)
  static const Color yellow5 = Color(0xfffbe882);

  /// yellow step 6 (light mode)
  static const Color yellow6 = Color(0xffeed879);

  /// yellow step 7 (light mode)
  static const Color yellow7 = Color(0xffdfc875);

  /// yellow step 8 (light mode)
  static const Color yellow8 = Color(0xffcfb050);

  /// yellow step 9 (light mode)
  static const Color yellow9 = Color(0xffffeb38);

  /// yellow step 10 (light mode)
  static const Color yellow10 = Color(0xfff9dd4a);

  /// yellow step 11 (light mode)
  static const Color yellow11 = Color(0xff997000);

  /// yellow step 12 (light mode)
  static const Color yellow12 = Color(0xff453b23);

  /// amber step 1 (light mode)
  static const Color amber1 = Color(0xfffefdfb);

  /// amber step 2 (light mode)
  static const Color amber2 = Color(0xfffdfbeb);

  /// amber step 3 (light mode)
  static const Color amber3 = Color(0xfffdf7c7);

  /// amber step 4 (light mode)
  static const Color amber4 = Color(0xfffcefa6);

  /// amber step 5 (light mode)
  static const Color amber5 = Color(0xfff7e686);

  /// amber step 6 (light mode)
  static const Color amber6 = Color(0xffefd781);

  /// amber step 7 (light mode)
  static const Color amber7 = Color(0xffe3c271);

  /// amber step 8 (light mode)
  static const Color amber8 = Color(0xffd9a64d);

  /// amber step 9 (light mode)
  static const Color amber9 = Color(0xffffc442);

  /// amber step 10 (light mode)
  static const Color amber10 = Color(0xfff5bd46);

  /// amber step 11 (light mode)
  static const Color amber11 = Color(0xffa36600);

  /// amber step 12 (light mode)
  static const Color amber12 = Color(0xff4b3525);

  /// gray step 1 (dark mode)
  static const Color darkGray1 = Color(0xff111111);

  /// gray step 2 (dark mode)
  static const Color darkGray2 = Color(0xff191919);

  /// gray step 3 (dark mode)
  static const Color darkGray3 = Color(0xff222222);

  /// gray step 4 (dark mode)
  static const Color darkGray4 = Color(0xff2a2a2a);

  /// gray step 5 (dark mode)
  static const Color darkGray5 = Color(0xff313131);

  /// gray step 6 (dark mode)
  static const Color darkGray6 = Color(0xff3a3a3a);

  /// gray step 7 (dark mode)
  static const Color darkGray7 = Color(0xff484848);

  /// gray step 8 (dark mode)
  static const Color darkGray8 = Color(0xff606060);

  /// gray step 9 (dark mode)
  static const Color darkGray9 = Color(0xff6e6e6e);

  /// gray step 10 (dark mode)
  static const Color darkGray10 = Color(0xff7b7b7b);

  /// gray step 11 (dark mode)
  static const Color darkGray11 = Color(0xffb4b4b4);

  /// gray step 12 (dark mode)
  static const Color darkGray12 = Color(0xffeeeeee);

  /// mauve step 1 (dark mode)
  static const Color darkMauve1 = Color(0xff121113);

  /// mauve step 2 (dark mode)
  static const Color darkMauve2 = Color(0xff1a191b);

  /// mauve step 3 (dark mode)
  static const Color darkMauve3 = Color(0xff232225);

  /// mauve step 4 (dark mode)
  static const Color darkMauve4 = Color(0xff2b292d);

  /// mauve step 5 (dark mode)
  static const Color darkMauve5 = Color(0xff323035);

  /// mauve step 6 (dark mode)
  static const Color darkMauve6 = Color(0xff3b393e);

  /// mauve step 7 (dark mode)
  static const Color darkMauve7 = Color(0xff49474d);

  /// mauve step 8 (dark mode)
  static const Color darkMauve8 = Color(0xff625f68);

  /// mauve step 9 (dark mode)
  static const Color darkMauve9 = Color(0xff6f6d77);

  /// mauve step 10 (dark mode)
  static const Color darkMauve10 = Color(0xff7c7a84);

  /// mauve step 11 (dark mode)
  static const Color darkMauve11 = Color(0xffb4b3bb);

  /// mauve step 12 (dark mode)
  static const Color darkMauve12 = Color(0xffeeeef0);

  /// slate step 1 (dark mode)
  static const Color darkSlate1 = Color(0xff111113);

  /// slate step 2 (dark mode)
  static const Color darkSlate2 = Color(0xff18191b);

  /// slate step 3 (dark mode)
  static const Color darkSlate3 = Color(0xff212225);

  /// slate step 4 (dark mode)
  static const Color darkSlate4 = Color(0xff282a2d);

  /// slate step 5 (dark mode)
  static const Color darkSlate5 = Color(0xff2f3135);

  /// slate step 6 (dark mode)
  static const Color darkSlate6 = Color(0xff373a3e);

  /// slate step 7 (dark mode)
  static const Color darkSlate7 = Color(0xff44474d);

  /// slate step 8 (dark mode)
  static const Color darkSlate8 = Color(0xff5b6168);

  /// slate step 9 (dark mode)
  static const Color darkSlate9 = Color(0xff6a6e76);

  /// slate step 10 (dark mode)
  static const Color darkSlate10 = Color(0xff787b83);

  /// slate step 11 (dark mode)
  static const Color darkSlate11 = Color(0xffb0b4ba);

  /// slate step 12 (dark mode)
  static const Color darkSlate12 = Color(0xffedeef0);

  /// sage step 1 (dark mode)
  static const Color darkSage1 = Color(0xff101211);

  /// sage step 2 (dark mode)
  static const Color darkSage2 = Color(0xff171918);

  /// sage step 3 (dark mode)
  static const Color darkSage3 = Color(0xff212221);

  /// sage step 4 (dark mode)
  static const Color darkSage4 = Color(0xff282a29);

  /// sage step 5 (dark mode)
  static const Color darkSage5 = Color(0xff2f3130);

  /// sage step 6 (dark mode)
  static const Color darkSage6 = Color(0xff383b39);

  /// sage step 7 (dark mode)
  static const Color darkSage7 = Color(0xff454947);

  /// sage step 8 (dark mode)
  static const Color darkSage8 = Color(0xff5c615f);

  /// sage step 9 (dark mode)
  static const Color darkSage9 = Color(0xff65706b);

  /// sage step 10 (dark mode)
  static const Color darkSage10 = Color(0xff747d79);

  /// sage step 11 (dark mode)
  static const Color darkSage11 = Color(0xffafb5b2);

  /// sage step 12 (dark mode)
  static const Color darkSage12 = Color(0xffeceeed);

  /// olive step 1 (dark mode)
  static const Color darkOlive1 = Color(0xff111210);

  /// olive step 2 (dark mode)
  static const Color darkOlive2 = Color(0xff181917);

  /// olive step 3 (dark mode)
  static const Color darkOlive3 = Color(0xff212220);

  /// olive step 4 (dark mode)
  static const Color darkOlive4 = Color(0xff282a27);

  /// olive step 5 (dark mode)
  static const Color darkOlive5 = Color(0xff2f312e);

  /// olive step 6 (dark mode)
  static const Color darkOlive6 = Color(0xff383a37);

  /// olive step 7 (dark mode)
  static const Color darkOlive7 = Color(0xff464844);

  /// olive step 8 (dark mode)
  static const Color darkOlive8 = Color(0xff5d615c);

  /// olive step 9 (dark mode)
  static const Color darkOlive9 = Color(0xff6a7067);

  /// olive step 10 (dark mode)
  static const Color darkOlive10 = Color(0xff777d75);

  /// olive step 11 (dark mode)
  static const Color darkOlive11 = Color(0xffb0b5ae);

  /// olive step 12 (dark mode)
  static const Color darkOlive12 = Color(0xffeceeec);

  /// sand step 1 (dark mode)
  static const Color darkSand1 = Color(0xff111110);

  /// sand step 2 (dark mode)
  static const Color darkSand2 = Color(0xff191918);

  /// sand step 3 (dark mode)
  static const Color darkSand3 = Color(0xff222221);

  /// sand step 4 (dark mode)
  static const Color darkSand4 = Color(0xff2a2a28);

  /// sand step 5 (dark mode)
  static const Color darkSand5 = Color(0xff31312f);

  /// sand step 6 (dark mode)
  static const Color darkSand6 = Color(0xff3b3a37);

  /// sand step 7 (dark mode)
  static const Color darkSand7 = Color(0xff494844);

  /// sand step 8 (dark mode)
  static const Color darkSand8 = Color(0xff62605b);

  /// sand step 9 (dark mode)
  static const Color darkSand9 = Color(0xff6f6d67);

  /// sand step 10 (dark mode)
  static const Color darkSand10 = Color(0xff7c7b74);

  /// sand step 11 (dark mode)
  static const Color darkSand11 = Color(0xffb4b3ad);

  /// sand step 12 (dark mode)
  static const Color darkSand12 = Color(0xffeeeeec);

  /// tomato step 1 (dark mode)
  static const Color darkTomato1 = Color(0xff171111);

  /// tomato step 2 (dark mode)
  static const Color darkTomato2 = Color(0xff1d1513);

  /// tomato step 3 (dark mode)
  static const Color darkTomato3 = Color(0xff341915);

  /// tomato step 4 (dark mode)
  static const Color darkTomato4 = Color(0xff481914);

  /// tomato step 5 (dark mode)
  static const Color darkTomato5 = Color(0xff56211a);

  /// tomato step 6 (dark mode)
  static const Color darkTomato6 = Color(0xff652e24);

  /// tomato step 7 (dark mode)
  static const Color darkTomato7 = Color(0xff7c3e31);

  /// tomato step 8 (dark mode)
  static const Color darkTomato8 = Color(0xffa0523f);

  /// tomato step 9 (dark mode)
  static const Color darkTomato9 = Color(0xffd4583b);

  /// tomato step 10 (dark mode)
  static const Color darkTomato10 = Color(0xffdc6a4c);

  /// tomato step 11 (dark mode)
  static const Color darkTomato11 = Color(0xffff9574);

  /// tomato step 12 (dark mode)
  static const Color darkTomato12 = Color(0xfff5d4cd);

  /// red step 1 (dark mode)
  static const Color darkRed1 = Color(0xff181111);

  /// red step 2 (dark mode)
  static const Color darkRed2 = Color(0xff1e1414);

  /// red step 3 (dark mode)
  static const Color darkRed3 = Color(0xff361519);

  /// red step 4 (dark mode)
  static const Color darkRed4 = Color(0xff49141d);

  /// red step 5 (dark mode)
  static const Color darkRed5 = Color(0xff591c24);

  /// red step 6 (dark mode)
  static const Color darkRed6 = Color(0xff6a292f);

  /// red step 7 (dark mode)
  static const Color darkRed7 = Color(0xff82393c);

  /// red step 8 (dark mode)
  static const Color darkRed8 = Color(0xffa84c4c);

  /// red step 9 (dark mode)
  static const Color darkRed9 = Color(0xffd45453);

  /// red step 10 (dark mode)
  static const Color darkRed10 = Color(0xffdc6763);

  /// red step 11 (dark mode)
  static const Color darkRed11 = Color(0xffff918c);

  /// red step 12 (dark mode)
  static const Color darkRed12 = Color(0xfff8d3d9);

  /// ruby step 1 (dark mode)
  static const Color darkRuby1 = Color(0xff181113);

  /// ruby step 2 (dark mode)
  static const Color darkRuby2 = Color(0xff1d1517);

  /// ruby step 3 (dark mode)
  static const Color darkRuby3 = Color(0xff35161e);

  /// ruby step 4 (dark mode)
  static const Color darkRuby4 = Color(0xff471725);

  /// ruby step 5 (dark mode)
  static const Color darkRuby5 = Color(0xff561f2e);

  /// ruby step 6 (dark mode)
  static const Color darkRuby6 = Color(0xff662a39);

  /// ruby step 7 (dark mode)
  static const Color darkRuby7 = Color(0xff7e3948);

  /// ruby step 8 (dark mode)
  static const Color darkRuby8 = Color(0xffa64b5c);

  /// ruby step 9 (dark mode)
  static const Color darkRuby9 = Color(0xffd45268);

  /// ruby step 10 (dark mode)
  static const Color darkRuby10 = Color(0xffdb6474);

  /// ruby step 11 (dark mode)
  static const Color darkRuby11 = Color(0xffff9196);

  /// ruby step 12 (dark mode)
  static const Color darkRuby12 = Color(0xfff7d4e0);

  /// crimson step 1 (dark mode)
  static const Color darkCrimson1 = Color(0xff181114);

  /// crimson step 2 (dark mode)
  static const Color darkCrimson2 = Color(0xff1e1418);

  /// crimson step 3 (dark mode)
  static const Color darkCrimson3 = Color(0xff341724);

  /// crimson step 4 (dark mode)
  static const Color darkCrimson4 = Color(0xff47162e);

  /// crimson step 5 (dark mode)
  static const Color darkCrimson5 = Color(0xff551d38);

  /// crimson step 6 (dark mode)
  static const Color darkCrimson6 = Color(0xff642944);

  /// crimson step 7 (dark mode)
  static const Color darkCrimson7 = Color(0xff7d3956);

  /// crimson step 8 (dark mode)
  static const Color darkCrimson8 = Color(0xffa34a6d);

  /// crimson step 9 (dark mode)
  static const Color darkCrimson9 = Color(0xffd74c81);

  /// crimson step 10 (dark mode)
  static const Color darkCrimson10 = Color(0xffdc5d89);

  /// crimson step 11 (dark mode)
  static const Color darkCrimson11 = Color(0xffff8fa8);

  /// crimson step 12 (dark mode)
  static const Color darkCrimson12 = Color(0xfff6d5e7);

  /// pink step 1 (dark mode)
  static const Color darkPink1 = Color(0xff181117);

  /// pink step 2 (dark mode)
  static const Color darkPink2 = Color(0xff1f131c);

  /// pink step 3 (dark mode)
  static const Color darkPink3 = Color(0xff32192e);

  /// pink step 4 (dark mode)
  static const Color darkPink4 = Color(0xff45183b);

  /// pink step 5 (dark mode)
  static const Color darkPink5 = Color(0xff522046);

  /// pink step 6 (dark mode)
  static const Color darkPink6 = Color(0xff612d53);

  /// pink step 7 (dark mode)
  static const Color darkPink7 = Color(0xff7a3d67);

  /// pink step 8 (dark mode)
  static const Color darkPink8 = Color(0xff9c4e82);

  /// pink step 9 (dark mode)
  static const Color darkPink9 = Color(0xffc64c9c);

  /// pink step 10 (dark mode)
  static const Color darkPink10 = Color(0xffce5ba4);

  /// pink step 11 (dark mode)
  static const Color darkPink11 = Color(0xffff88c7);

  /// pink step 12 (dark mode)
  static const Color darkPink12 = Color(0xfff6d3e9);

  /// plum step 1 (dark mode)
  static const Color darkPlum1 = Color(0xff171117);

  /// plum step 2 (dark mode)
  static const Color darkPlum2 = Color(0xff1e141f);

  /// plum step 3 (dark mode)
  static const Color darkPlum3 = Color(0xff311b34);

  /// plum step 4 (dark mode)
  static const Color darkPlum4 = Color(0xff401f45);

  /// plum step 5 (dark mode)
  static const Color darkPlum5 = Color(0xff4b2751);

  /// plum step 6 (dark mode)
  static const Color darkPlum6 = Color(0xff57325f);

  /// plum step 7 (dark mode)
  static const Color darkPlum7 = Color(0xff6c4376);

  /// plum step 8 (dark mode)
  static const Color darkPlum8 = Color(0xff8a5798);

  /// plum step 9 (dark mode)
  static const Color darkPlum9 = Color(0xff9f50b5);

  /// plum step 10 (dark mode)
  static const Color darkPlum10 = Color(0xffaa5dbf);

  /// plum step 11 (dark mode)
  static const Color darkPlum11 = Color(0xffdb9aee);

  /// plum step 12 (dark mode)
  static const Color darkPlum12 = Color(0xffefd5f2);

  /// purple step 1 (dark mode)
  static const Color darkPurple1 = Color(0xff17111a);

  /// purple step 2 (dark mode)
  static const Color darkPurple2 = Color(0xff1d1522);

  /// purple step 3 (dark mode)
  static const Color darkPurple3 = Color(0xff2d1d39);

  /// purple step 4 (dark mode)
  static const Color darkPurple4 = Color(0xff39234c);

  /// purple step 5 (dark mode)
  static const Color darkPurple5 = Color(0xff432b59);

  /// purple step 6 (dark mode)
  static const Color darkPurple6 = Color(0xff4f3568);

  /// purple step 7 (dark mode)
  static const Color darkPurple7 = Color(0xff61447e);

  /// purple step 8 (dark mode)
  static const Color darkPurple8 = Color(0xff7d59a5);

  /// purple step 9 (dark mode)
  static const Color darkPurple9 = Color(0xff8551c0);

  /// purple step 10 (dark mode)
  static const Color darkPurple10 = Color(0xff915fca);

  /// purple step 11 (dark mode)
  static const Color darkPurple11 = Color(0xffcc9eff);

  /// purple step 12 (dark mode)
  static const Color darkPurple12 = Color(0xffe9daf8);

  /// violet step 1 (dark mode)
  static const Color darkViolet1 = Color(0xff14121e);

  /// violet step 2 (dark mode)
  static const Color darkViolet2 = Color(0xff1a1524);

  /// violet step 3 (dark mode)
  static const Color darkViolet3 = Color(0xff271f41);

  /// violet step 4 (dark mode)
  static const Color darkViolet4 = Color(0xff312658);

  /// violet step 5 (dark mode)
  static const Color darkViolet5 = Color(0xff3a2e65);

  /// violet step 6 (dark mode)
  static const Color darkViolet6 = Color(0xff453972);

  /// violet step 7 (dark mode)
  static const Color darkViolet7 = Color(0xff534787);

  /// violet step 8 (dark mode)
  static const Color darkViolet8 = Color(0xff6658a7);

  /// violet step 9 (dark mode)
  static const Color darkViolet9 = Color(0xff6a57c8);

  /// violet step 10 (dark mode)
  static const Color darkViolet10 = Color(0xff7a67d2);

  /// violet step 11 (dark mode)
  static const Color darkViolet11 = Color(0xffb8a6ff);

  /// violet step 12 (dark mode)
  static const Color darkViolet12 = Color(0xffe1ddfb);

  /// iris step 1 (dark mode)
  static const Color darkIris1 = Color(0xff13131d);

  /// iris step 2 (dark mode)
  static const Color darkIris2 = Color(0xff171624);

  /// iris step 3 (dark mode)
  static const Color darkIris3 = Color(0xff212245);

  /// iris step 4 (dark mode)
  static const Color darkIris4 = Color(0xff272a61);

  /// iris step 5 (dark mode)
  static const Color darkIris5 = Color(0xff313370);

  /// iris step 6 (dark mode)
  static const Color darkIris6 = Color(0xff3d3d7d);

  /// iris step 7 (dark mode)
  static const Color darkIris7 = Color(0xff4a4a90);

  /// iris step 8 (dark mode)
  static const Color darkIris8 = Color(0xff5958ac);

  /// iris step 9 (dark mode)
  static const Color darkIris9 = Color(0xff5b5bcf);

  /// iris step 10 (dark mode)
  static const Color darkIris10 = Color(0xff6d6ad7);

  /// iris step 11 (dark mode)
  static const Color darkIris11 = Color(0xffafa9ff);

  /// iris step 12 (dark mode)
  static const Color darkIris12 = Color(0xffe0dffb);

  /// indigo step 1 (dark mode)
  static const Color darkIndigo1 = Color(0xff11131e);

  /// indigo step 2 (dark mode)
  static const Color darkIndigo2 = Color(0xff151725);

  /// indigo step 3 (dark mode)
  static const Color darkIndigo3 = Color(0xff1b2446);

  /// indigo step 4 (dark mode)
  static const Color darkIndigo4 = Color(0xff212e5e);

  /// indigo step 5 (dark mode)
  static const Color darkIndigo5 = Color(0xff2a3870);

  /// indigo step 6 (dark mode)
  static const Color darkIndigo6 = Color(0xff344380);

  /// indigo step 7 (dark mode)
  static const Color darkIndigo7 = Color(0xff3e4f93);

  /// indigo step 8 (dark mode)
  static const Color darkIndigo8 = Color(0xff495cac);

  /// indigo step 9 (dark mode)
  static const Color darkIndigo9 = Color(0xff4662d5);

  /// indigo step 10 (dark mode)
  static const Color darkIndigo10 = Color(0xff5a71dd);

  /// indigo step 11 (dark mode)
  static const Color darkIndigo11 = Color(0xffa1b0ff);

  /// indigo step 12 (dark mode)
  static const Color darkIndigo12 = Color(0xffd8e1fc);

  /// blue step 1 (dark mode)
  static const Color darkBlue1 = Color(0xff0f151f);

  /// blue step 2 (dark mode)
  static const Color darkBlue2 = Color(0xff121925);

  /// blue step 3 (dark mode)
  static const Color darkBlue3 = Color(0xff142745);

  /// blue step 4 (dark mode)
  static const Color darkBlue4 = Color(0xff08325e);

  /// blue step 5 (dark mode)
  static const Color darkBlue5 = Color(0xff143e70);

  /// blue step 6 (dark mode)
  static const Color darkBlue6 = Color(0xff244c82);

  /// blue step 7 (dark mode)
  static const Color darkBlue7 = Color(0xff325c99);

  /// blue step 8 (dark mode)
  static const Color darkBlue8 = Color(0xff3d6fb8);

  /// blue step 9 (dark mode)
  static const Color darkBlue9 = Color(0xff3f8ef7);

  /// blue step 10 (dark mode)
  static const Color darkBlue10 = Color(0xff589cf8);

  /// blue step 11 (dark mode)
  static const Color darkBlue11 = Color(0xff7db8ff);

  /// blue step 12 (dark mode)
  static const Color darkBlue12 = Color(0xffc9e5fc);

  /// cyan step 1 (dark mode)
  static const Color darkCyan1 = Color(0xff0e1619);

  /// cyan step 2 (dark mode)
  static const Color darkCyan2 = Color(0xff121b1f);

  /// cyan step 3 (dark mode)
  static const Color darkCyan3 = Color(0xff132b35);

  /// cyan step 4 (dark mode)
  static const Color darkCyan4 = Color(0xff103747);

  /// cyan step 5 (dark mode)
  static const Color darkCyan5 = Color(0xff174456);

  /// cyan step 6 (dark mode)
  static const Color darkCyan6 = Color(0xff235366);

  /// cyan step 7 (dark mode)
  static const Color darkCyan7 = Color(0xff2f657b);

  /// cyan step 8 (dark mode)
  static const Color darkCyan8 = Color(0xff3b7e99);

  /// cyan step 9 (dark mode)
  static const Color darkCyan9 = Color(0xff48a0c3);

  /// cyan step 10 (dark mode)
  static const Color darkCyan10 = Color(0xff54accc);

  /// cyan step 11 (dark mode)
  static const Color darkCyan11 = Color(0xff72c9e2);

  /// cyan step 12 (dark mode)
  static const Color darkCyan12 = Color(0xffc1eaf5);

  /// teal step 1 (dark mode)
  static const Color darkTeal1 = Color(0xff0f1514);

  /// teal step 2 (dark mode)
  static const Color darkTeal2 = Color(0xff131c1b);

  /// teal step 3 (dark mode)
  static const Color darkTeal3 = Color(0xff162d2a);

  /// teal step 4 (dark mode)
  static const Color darkTeal4 = Color(0xff163a37);

  /// teal step 5 (dark mode)
  static const Color darkTeal5 = Color(0xff1f4743);

  /// teal step 6 (dark mode)
  static const Color darkTeal6 = Color(0xff295550);

  /// teal step 7 (dark mode)
  static const Color darkTeal7 = Color(0xff346861);

  /// teal step 8 (dark mode)
  static const Color darkTeal8 = Color(0xff3e7d74);

  /// teal step 9 (dark mode)
  static const Color darkTeal9 = Color(0xff4ca294);

  /// teal step 10 (dark mode)
  static const Color darkTeal10 = Color(0xff51b09e);

  /// teal step 11 (dark mode)
  static const Color darkTeal11 = Color(0xff63d5b7);

  /// teal step 12 (dark mode)
  static const Color darkTeal12 = Color(0xffbbeede);

  /// jade step 1 (dark mode)
  static const Color darkJade1 = Color(0xff0f1512);

  /// jade step 2 (dark mode)
  static const Color darkJade2 = Color(0xff141c18);

  /// jade step 3 (dark mode)
  static const Color darkJade3 = Color(0xff172d23);

  /// jade step 4 (dark mode)
  static const Color darkJade4 = Color(0xff1a3a2d);

  /// jade step 5 (dark mode)
  static const Color darkJade5 = Color(0xff224738);

  /// jade step 6 (dark mode)
  static const Color darkJade6 = Color(0xff2c5546);

  /// jade step 7 (dark mode)
  static const Color darkJade7 = Color(0xff386755);

  /// jade step 8 (dark mode)
  static const Color darkJade8 = Color(0xff437c69);

  /// jade step 9 (dark mode)
  static const Color darkJade9 = Color(0xff51a185);

  /// jade step 10 (dark mode)
  static const Color darkJade10 = Color(0xff56ad8e);

  /// jade step 11 (dark mode)
  static const Color darkJade11 = Color(0xff66d5a7);

  /// jade step 12 (dark mode)
  static const Color darkJade12 = Color(0xffbbeed6);

  /// green step 1 (dark mode)
  static const Color darkGreen1 = Color(0xff101512);

  /// green step 2 (dark mode)
  static const Color darkGreen2 = Color(0xff141b17);

  /// green step 3 (dark mode)
  static const Color darkGreen3 = Color(0xff1a2c22);

  /// green step 4 (dark mode)
  static const Color darkGreen4 = Color(0xff1d3a2a);

  /// green step 5 (dark mode)
  static const Color darkGreen5 = Color(0xff254835);

  /// green step 6 (dark mode)
  static const Color darkGreen6 = Color(0xff2f5640);

  /// green step 7 (dark mode)
  static const Color darkGreen7 = Color(0xff3a674c);

  /// green step 8 (dark mode)
  static const Color darkGreen8 = Color(0xff457a5a);

  /// green step 9 (dark mode)
  static const Color darkGreen9 = Color(0xff55a271);

  /// green step 10 (dark mode)
  static const Color darkGreen10 = Color(0xff5bae79);

  /// green step 11 (dark mode)
  static const Color darkGreen11 = Color(0xff6fd392);

  /// green step 12 (dark mode)
  static const Color darkGreen12 = Color(0xffbeefce);

  /// grass step 1 (dark mode)
  static const Color darkGrass1 = Color(0xff101511);

  /// grass step 2 (dark mode)
  static const Color darkGrass2 = Color(0xff151a16);

  /// grass step 3 (dark mode)
  static const Color darkGrass3 = Color(0xff1e2a1f);

  /// grass step 4 (dark mode)
  static const Color darkGrass4 = Color(0xff243926);

  /// grass step 5 (dark mode)
  static const Color darkGrass5 = Color(0xff2d472f);

  /// grass step 6 (dark mode)
  static const Color darkGrass6 = Color(0xff375639);

  /// grass step 7 (dark mode)
  static const Color darkGrass7 = Color(0xff426643);

  /// grass step 8 (dark mode)
  static const Color darkGrass8 = Color(0xff4d784e);

  /// grass step 9 (dark mode)
  static const Color darkGrass9 = Color(0xff61a560);

  /// grass step 10 (dark mode)
  static const Color darkGrass10 = Color(0xff6db16d);

  /// grass step 11 (dark mode)
  static const Color darkGrass11 = Color(0xff88ce8a);

  /// grass step 12 (dark mode)
  static const Color darkGrass12 = Color(0xffcbefc6);

  /// brown step 1 (dark mode)
  static const Color darkBrown1 = Color(0xff12110f);

  /// brown step 2 (dark mode)
  static const Color darkBrown2 = Color(0xff1b1816);

  /// brown step 3 (dark mode)
  static const Color darkBrown3 = Color(0xff27211d);

  /// brown step 4 (dark mode)
  static const Color darkBrown4 = Color(0xff312923);

  /// brown step 5 (dark mode)
  static const Color darkBrown5 = Color(0xff3c3129);

  /// brown step 6 (dark mode)
  static const Color darkBrown6 = Color(0xff4a3c31);

  /// brown step 7 (dark mode)
  static const Color darkBrown7 = Color(0xff5d4b3b);

  /// brown step 8 (dark mode)
  static const Color darkBrown8 = Color(0xff786049);

  /// brown step 9 (dark mode)
  static const Color darkBrown9 = Color(0xffa6815e);

  /// brown step 10 (dark mode)
  static const Color darkBrown10 = Color(0xffb28e6c);

  /// brown step 11 (dark mode)
  static const Color darkBrown11 = Color(0xffd5b698);

  /// brown step 12 (dark mode)
  static const Color darkBrown12 = Color(0xffefe2cd);

  /// orange step 1 (dark mode)
  static const Color darkOrange1 = Color(0xff16120f);

  /// orange step 2 (dark mode)
  static const Color darkOrange2 = Color(0xff1d1710);

  /// orange step 3 (dark mode)
  static const Color darkOrange3 = Color(0xff301f0e);

  /// orange step 4 (dark mode)
  static const Color darkOrange4 = Color(0xff432200);

  /// orange step 5 (dark mode)
  static const Color darkOrange5 = Color(0xff502b04);

  /// orange step 6 (dark mode)
  static const Color darkOrange6 = Color(0xff603816);

  /// orange step 7 (dark mode)
  static const Color darkOrange7 = Color(0xff774825);

  /// orange step 8 (dark mode)
  static const Color darkOrange8 = Color(0xff995c33);

  /// orange step 9 (dark mode)
  static const Color darkOrange9 = Color(0xffe67333);

  /// orange step 10 (dark mode)
  static const Color darkOrange10 = Color(0xfffa823b);

  /// orange step 11 (dark mode)
  static const Color darkOrange11 = Color(0xffffa161);

  /// orange step 12 (dark mode)
  static const Color darkOrange12 = Color(0xfffae1c6);

  /// sky step 1 (dark mode)
  static const Color darkSky1 = Color(0xff0e141e);

  /// sky step 2 (dark mode)
  static const Color darkSky2 = Color(0xff131a26);

  /// sky step 3 (dark mode)
  static const Color darkSky3 = Color(0xff17273e);

  /// sky step 4 (dark mode)
  static const Color darkSky4 = Color(0xff1b3552);

  /// sky step 5 (dark mode)
  static const Color darkSky5 = Color(0xff224364);

  /// sky step 6 (dark mode)
  static const Color darkSky6 = Color(0xff2b5278);

  /// sky step 7 (dark mode)
  static const Color darkSky7 = Color(0xff34648e);

  /// sky step 8 (dark mode)
  static const Color darkSky8 = Color(0xff3b7aaa);

  /// sky step 9 (dark mode)
  static const Color darkSky9 = Color(0xff95e0fb);

  /// sky step 10 (dark mode)
  static const Color darkSky10 = Color(0xffb7ecfd);

  /// sky step 11 (dark mode)
  static const Color darkSky11 = Color(0xff89c5ec);

  /// sky step 12 (dark mode)
  static const Color darkSky12 = Color(0xffccf1fd);

  /// mint step 1 (dark mode)
  static const Color darkMint1 = Color(0xff0f1515);

  /// mint step 2 (dark mode)
  static const Color darkMint2 = Color(0xff111b1b);

  /// mint step 3 (dark mode)
  static const Color darkMint3 = Color(0xff142b2b);

  /// mint step 4 (dark mode)
  static const Color darkMint4 = Color(0xff113938);

  /// mint step 5 (dark mode)
  static const Color darkMint5 = Color(0xff1b4643);

  /// mint step 6 (dark mode)
  static const Color darkMint6 = Color(0xff275550);

  /// mint step 7 (dark mode)
  static const Color darkMint7 = Color(0xff35675f);

  /// mint step 8 (dark mode)
  static const Color darkMint8 = Color(0xff427d70);

  /// mint step 9 (dark mode)
  static const Color darkMint9 = Color(0xff9ee8d5);

  /// mint step 10 (dark mode)
  static const Color darkMint10 = Color(0xffb9f3e5);

  /// mint step 11 (dark mode)
  static const Color darkMint11 = Color(0xff7bd2bb);

  /// mint step 12 (dark mode)
  static const Color darkMint12 = Color(0xffcef4e2);

  /// lime step 1 (dark mode)
  static const Color darkLime1 = Color(0xff11130c);

  /// lime step 2 (dark mode)
  static const Color darkLime2 = Color(0xff161a11);

  /// lime step 3 (dark mode)
  static const Color darkLime3 = Color(0xff212919);

  /// lime step 4 (dark mode)
  static const Color darkLime4 = Color(0xff2c3720);

  /// lime step 5 (dark mode)
  static const Color darkLime5 = Color(0xff364427);

  /// lime step 6 (dark mode)
  static const Color darkLime6 = Color(0xff42522e);

  /// lime step 7 (dark mode)
  static const Color darkLime7 = Color(0xff4e6237);

  /// lime step 8 (dark mode)
  static const Color darkLime8 = Color(0xff5d7440);

  /// lime step 9 (dark mode)
  static const Color darkLime9 = Color(0xffc7ed77);

  /// lime step 10 (dark mode)
  static const Color darkLime10 = Color(0xffddfe84);

  /// lime step 11 (dark mode)
  static const Color darkLime11 = Color(0xffc5e47c);

  /// lime step 12 (dark mode)
  static const Color darkLime12 = Color(0xffe7f6c0);

  /// yellow step 1 (dark mode)
  static const Color darkYellow1 = Color(0xff14120c);

  /// yellow step 2 (dark mode)
  static const Color darkYellow2 = Color(0xff1a1810);

  /// yellow step 3 (dark mode)
  static const Color darkYellow3 = Color(0xff2b230a);

  /// yellow step 4 (dark mode)
  static const Color darkYellow4 = Color(0xff352b00);

  /// yellow step 5 (dark mode)
  static const Color darkYellow5 = Color(0xff413500);

  /// yellow step 6 (dark mode)
  static const Color darkYellow6 = Color(0xff4f4312);

  /// yellow step 7 (dark mode)
  static const Color darkYellow7 = Color(0xff635422);

  /// yellow step 8 (dark mode)
  static const Color darkYellow8 = Color(0xff7f6b2e);

  /// yellow step 9 (dark mode)
  static const Color darkYellow9 = Color(0xffffeb38);

  /// yellow step 10 (dark mode)
  static const Color darkYellow10 = Color(0xffffff74);

  /// yellow step 11 (dark mode)
  static const Color darkYellow11 = Color(0xfff2e264);

  /// yellow step 12 (dark mode)
  static const Color darkYellow12 = Color(0xfff5eeba);

  /// amber step 1 (dark mode)
  static const Color darkAmber1 = Color(0xff15120d);

  /// amber step 2 (dark mode)
  static const Color darkAmber2 = Color(0xff1c1810);

  /// amber step 3 (dark mode)
  static const Color darkAmber3 = Color(0xff2d210c);

  /// amber step 4 (dark mode)
  static const Color darkAmber4 = Color(0xff3d2800);

  /// amber step 5 (dark mode)
  static const Color darkAmber5 = Color(0xff4a3100);

  /// amber step 6 (dark mode)
  static const Color darkAmber6 = Color(0xff583e13);

  /// amber step 7 (dark mode)
  static const Color darkAmber7 = Color(0xff6c5024);

  /// amber step 8 (dark mode)
  static const Color darkAmber8 = Color(0xff886630);

  /// amber step 9 (dark mode)
  static const Color darkAmber9 = Color(0xffffc442);

  /// amber step 10 (dark mode)
  static const Color darkAmber10 = Color(0xffffde26);

  /// amber step 11 (dark mode)
  static const Color darkAmber11 = Color(0xffffcc4a);

  /// amber step 12 (dark mode)
  static const Color darkAmber12 = Color(0xfffbe8b9);

}

class LightColors {
  const LightColors();

  /// gray color scale (light mode)
  static const List<Color> gray = [Color(0xfffcfcfc), Color(0xfff9f9f9), Color(0xffefefef), Color(0xffe8e8e8), Color(0xffe0e0e0), Color(0xffd8d8d8), Color(0xffcecece), Color(0xffbbbbbb), Color(0xff8d8d8d), Color(0xff838383), Color(0xff646464), Color(0xff202020)];

  /// mauve color scale (light mode)
  static const List<Color> mauve = [Color(0xfffdfcfd), Color(0xfffaf9fb), Color(0xfff1eff3), Color(0xffe9e7ec), Color(0xffe2dfe6), Color(0xffdad8df), Color(0xffd0cdd6), Color(0xffbbbac6), Color(0xff8e8c98), Color(0xff83828d), Color(0xff65636c), Color(0xff211f25)];

  /// slate color scale (light mode)
  static const List<Color> slate = [Color(0xfffcfcfd), Color(0xfff9f9fb), Color(0xfff0f0f3), Color(0xffe8e8ec), Color(0xffe0e1e6), Color(0xffd9d9df), Color(0xffcdced6), Color(0xffb9bbc5), Color(0xff8b8d97), Color(0xff80838c), Color(0xff61646b), Color(0xff1d2024)];

  /// sage color scale (light mode)
  static const List<Color> sage = [Color(0xfffbfdfc), Color(0xfff7f9f8), Color(0xffeef1f0), Color(0xffe7e9e8), Color(0xffdfe2e0), Color(0xffd7dad8), Color(0xffcccfce), Color(0xffb9bcbb), Color(0xff878e8b), Color(0xff7d8381), Color(0xff606563), Color(0xff1b211e)];

  /// olive color scale (light mode)
  static const List<Color> olive = [Color(0xfffcfdfc), Color(0xfff8faf8), Color(0xffeff1ef), Color(0xffe7e9e7), Color(0xffe0e2df), Color(0xffd8dad7), Color(0xffcdcfcc), Color(0xffb9bcb8), Color(0xff8a8e88), Color(0xff80837d), Color(0xff61655f), Color(0xff1e211c)];

  /// sand color scale (light mode)
  static const List<Color> sand = [Color(0xfffdfdfc), Color(0xfff9f9f8), Color(0xfff0f0ef), Color(0xffe9e9e6), Color(0xffe2e1df), Color(0xffdad9d6), Color(0xffcfcfca), Color(0xffbcbbb6), Color(0xff8d8d87), Color(0xff82827c), Color(0xff63635e), Color(0xff21201c)];

  /// tomato color scale (light mode)
  static const List<Color> tomato = [Color(0xfffefcfc), Color(0xfffdf8f7), Color(0xfffbece8), Color(0xfffeddd5), Color(0xfffacfc4), Color(0xfff3bfb2), Color(0xffeaac9c), Color(0xffdf9380), Color(0xffd4583b), Color(0xffcd5033), Color(0xffc14227), Color(0xff552a22)];

  /// red color scale (light mode)
  static const List<Color> red = [Color(0xfffefcfc), Color(0xfffef8f8), Color(0xfffbecec), Color(0xffffdddd), Color(0xfffbcfcf), Color(0xfff4c0bf), Color(0xffe9acab), Color(0xffde9392), Color(0xffd45453), Color(0xffcb4b49), Color(0xffbe3c39), Color(0xff5c1d24)];

  /// ruby color scale (light mode)
  static const List<Color> ruby = [Color(0xfffefcfd), Color(0xfffef8f8), Color(0xfffbebed), Color(0xfffcdee2), Color(0xfff7d0d6), Color(0xffefc1c8), Color(0xffe5afb8), Color(0xffd996a3), Color(0xffd45268), Color(0xffcb4960), Color(0xffba364f), Color(0xff5c1d2c)];

  /// crimson color scale (light mode)
  static const List<Color> crimson = [Color(0xfffefcfd), Color(0xfffdf7f9), Color(0xfffceaf0), Color(0xfff9dde7), Color(0xfff3cfdc), Color(0xffebc1d0), Color(0xffe0aec2), Color(0xffd597b1), Color(0xffd74c81), Color(0xffce4477), Color(0xffba3263), Color(0xff5a1c38)];

  /// pink color scale (light mode)
  static const List<Color> pink = [Color(0xfffefcfe), Color(0xfffdf7fb), Color(0xfffaeaf5), Color(0xfff6ddee), Color(0xffefd0e5), Color(0xffe7c1db), Color(0xffdeaecf), Color(0xffd296c0), Color(0xffc64c9c), Color(0xffbf4594), Color(0xffb23887), Color(0xff5d1a47)];

  /// plum color scale (light mode)
  static const List<Color> plum = [Color(0xfffefcff), Color(0xfffcf8fc), Color(0xfff8ebfa), Color(0xfff3dff6), Color(0xffecd2f1), Color(0xffe3c3ea), Color(0xffd6afe0), Color(0xffc694d4), Color(0xff9f50b5), Color(0xff964aaa), Color(0xff8a439e), Color(0xff4c1d5a)];

  /// purple color scale (light mode)
  static const List<Color> purple = [Color(0xfffefcfe), Color(0xfffbf8fd), Color(0xfff6edfc), Color(0xffefe2fa), Color(0xffe7d5f6), Color(0xffdbc5f0), Color(0xffccb0e8), Color(0xffb795df), Color(0xff8551c0), Color(0xff7b4ab3), Color(0xff7948af), Color(0xff3c225d)];

  /// violet color scale (light mode)
  static const List<Color> violet = [Color(0xfffdfcfe), Color(0xfff9f8fe), Color(0xfff3f0fd), Color(0xffeae5ff), Color(0xffdfd9ff), Color(0xffd2cafa), Color(0xffc0b6f0), Color(0xffa79ae6), Color(0xff6a57c8), Color(0xff614ebd), Color(0xff6251b3), Color(0xff2e265c)];

  /// iris color scale (light mode)
  static const List<Color> iris = [Color(0xfffdfdff), Color(0xfff8f8fe), Color(0xfff0f1fd), Color(0xffe6e7ff), Color(0xffdbdcff), Color(0xffcccdfc), Color(0xffb8b9f4), Color(0xff9c9eea), Color(0xff5b5bcf), Color(0xff5151c5), Color(0xff5653bf), Color(0xff27295f)];

  /// indigo color scale (light mode)
  static const List<Color> indigo = [Color(0xfffdfdfe), Color(0xfff8f9fe), Color(0xffeef2fd), Color(0xffe2e9ff), Color(0xffd4deff), Color(0xffc4d0fe), Color(0xffafbdf4), Color(0xff91a3ea), Color(0xff4662d5), Color(0xff3c57cc), Color(0xff415ac1), Color(0xff222d59)];

  /// blue color scale (light mode)
  static const List<Color> blue = [Color(0xfffbfdff), Color(0xfff5fafe), Color(0xffe9f4fd), Color(0xffdaeeff), Color(0xffc9e4fe), Color(0xffb5d7f9), Color(0xff9bc6f1), Color(0xff73afea), Color(0xff3f8ef7), Color(0xff3c85e9), Color(0xff2670d6), Color(0xff1a3161)];

  /// cyan color scale (light mode)
  static const List<Color> cyan = [Color(0xfffafdfe), Color(0xfff4fafb), Color(0xffe2f6f9), Color(0xffd1f0f5), Color(0xffc0e7ee), Color(0xffabdce6), Color(0xff90ccda), Color(0xff63b6cb), Color(0xff48a0c3), Color(0xff4395b5), Color(0xff147aa1), Color(0xff1c3b47)];

  /// teal color scale (light mode)
  static const List<Color> teal = [Color(0xfffbfefd), Color(0xfff4fbf9), Color(0xffe4f8f3), Color(0xffd4f2eb), Color(0xffc2e9e0), Color(0xffaedcd2), Color(0xff94cbc1), Color(0xff6eb7ab), Color(0xff4ca294), Color(0xff46998a), Color(0xff14806e), Color(0xff1c3c38)];

  /// jade color scale (light mode)
  static const List<Color> jade = [Color(0xfffbfefd), Color(0xfff5fbf7), Color(0xffe9f6ee), Color(0xffdbf0e4), Color(0xffcbe8d8), Color(0xffb6dcca), Color(0xff9acdb7), Color(0xff70b8a0), Color(0xff51a185), Color(0xff4c977c), Color(0xff26805e), Color(0xff243a31)];

  /// green color scale (light mode)
  static const List<Color> green = [Color(0xfffbfefc), Color(0xfff6fbf7), Color(0xffe9f6ec), Color(0xffdbf0e0), Color(0xffcbe7d3), Color(0xffb7dcc2), Color(0xff9cccac), Color(0xff73b68f), Color(0xff55a271), Color(0xff4f986a), Color(0xff308052), Color(0xff223a2e)];

  /// grass color scale (light mode)
  static const List<Color> grass = [Color(0xfffbfefb), Color(0xfff6fbf6), Color(0xffebf6ea), Color(0xffdef0dd), Color(0xffcfe8cd), Color(0xffbbdcb9), Color(0xffa0cd9f), Color(0xff7ab87b), Color(0xff61a560), Color(0xff589857), Color(0xff437c43), Color(0xff273b27)];

  /// brown color scale (light mode)
  static const List<Color> brown = [Color(0xfffefdfc), Color(0xfffcf9f6), Color(0xfff5efe8), Color(0xffeee5da), Color(0xffe8dacb), Color(0xffe0ceba), Color(0xffd6bda3), Color(0xffc7a583), Color(0xffa6815e), Color(0xff997758), Color(0xff7c5f49), Color(0xff3c342f)];

  /// orange color scale (light mode)
  static const List<Color> orange = [Color(0xfffefcfb), Color(0xfffdf7ee), Color(0xfffcefd9), Color(0xffffdfaf), Color(0xffffd195), Color(0xfff9c48b), Color(0xffeab17c), Color(0xffe09861), Color(0xffe67333), Color(0xffde682a), Color(0xffc25700), Color(0xff522f20)];

  /// sky color scale (light mode)
  static const List<Color> sky = [Color(0xfffafeff), Color(0xfff3fafc), Color(0xffe5f6fc), Color(0xffd7eff9), Color(0xffc6e6f3), Color(0xffb3d9eb), Color(0xff9ac8e0), Color(0xff75b1d3), Color(0xff95e0fb), Color(0xff8ed7f5), Color(0xff31729a), Color(0xff253d54)];

  /// mint color scale (light mode)
  static const List<Color> mint = [Color(0xfffafefd), Color(0xfff4fbf9), Color(0xffe2f8f2), Color(0xffd1f3ea), Color(0xffbeeadf), Color(0xffaaded1), Color(0xff91cdbe), Color(0xff6bb9a5), Color(0xff9ee8d5), Color(0xff95decb), Color(0xff347665), Color(0xff23423c)];

  /// lime color scale (light mode)
  static const List<Color> lime = [Color(0xfffcfdfa), Color(0xfff9faf3), Color(0xffeff6d9), Color(0xffe4f0c2), Color(0xffd7e6ad), Color(0xffc6d999), Color(0xffb1c882), Color(0xff95b460), Color(0xffc7ed77), Color(0xffbbe465), Color(0xff627b3a), Color(0xff394021)];

  /// yellow color scale (light mode)
  static const List<Color> yellow = [Color(0xfffdfdf9), Color(0xfffefceb), Color(0xfffefabf), Color(0xfffdf3a0), Color(0xfffbe882), Color(0xffeed879), Color(0xffdfc875), Color(0xffcfb050), Color(0xffffeb38), Color(0xfff9dd4a), Color(0xff997000), Color(0xff453b23)];

  /// amber color scale (light mode)
  static const List<Color> amber = [Color(0xfffefdfb), Color(0xfffdfbeb), Color(0xfffdf7c7), Color(0xfffcefa6), Color(0xfff7e686), Color(0xffefd781), Color(0xffe3c271), Color(0xffd9a64d), Color(0xffffc442), Color(0xfff5bd46), Color(0xffa36600), Color(0xff4b3525)];

}

class DarkColors {
  const DarkColors();

  /// gray color scale (dark mode)
  static const List<Color> gray = [Color(0xff111111), Color(0xff191919), Color(0xff222222), Color(0xff2a2a2a), Color(0xff313131), Color(0xff3a3a3a), Color(0xff484848), Color(0xff606060), Color(0xff6e6e6e), Color(0xff7b7b7b), Color(0xffb4b4b4), Color(0xffeeeeee)];

  /// mauve color scale (dark mode)
  static const List<Color> mauve = [Color(0xff121113), Color(0xff1a191b), Color(0xff232225), Color(0xff2b292d), Color(0xff323035), Color(0xff3b393e), Color(0xff49474d), Color(0xff625f68), Color(0xff6f6d77), Color(0xff7c7a84), Color(0xffb4b3bb), Color(0xffeeeef0)];

  /// slate color scale (dark mode)
  static const List<Color> slate = [Color(0xff111113), Color(0xff18191b), Color(0xff212225), Color(0xff282a2d), Color(0xff2f3135), Color(0xff373a3e), Color(0xff44474d), Color(0xff5b6168), Color(0xff6a6e76), Color(0xff787b83), Color(0xffb0b4ba), Color(0xffedeef0)];

  /// sage color scale (dark mode)
  static const List<Color> sage = [Color(0xff101211), Color(0xff171918), Color(0xff212221), Color(0xff282a29), Color(0xff2f3130), Color(0xff383b39), Color(0xff454947), Color(0xff5c615f), Color(0xff65706b), Color(0xff747d79), Color(0xffafb5b2), Color(0xffeceeed)];

  /// olive color scale (dark mode)
  static const List<Color> olive = [Color(0xff111210), Color(0xff181917), Color(0xff212220), Color(0xff282a27), Color(0xff2f312e), Color(0xff383a37), Color(0xff464844), Color(0xff5d615c), Color(0xff6a7067), Color(0xff777d75), Color(0xffb0b5ae), Color(0xffeceeec)];

  /// sand color scale (dark mode)
  static const List<Color> sand = [Color(0xff111110), Color(0xff191918), Color(0xff222221), Color(0xff2a2a28), Color(0xff31312f), Color(0xff3b3a37), Color(0xff494844), Color(0xff62605b), Color(0xff6f6d67), Color(0xff7c7b74), Color(0xffb4b3ad), Color(0xffeeeeec)];

  /// tomato color scale (dark mode)
  static const List<Color> tomato = [Color(0xff171111), Color(0xff1d1513), Color(0xff341915), Color(0xff481914), Color(0xff56211a), Color(0xff652e24), Color(0xff7c3e31), Color(0xffa0523f), Color(0xffd4583b), Color(0xffdc6a4c), Color(0xffff9574), Color(0xfff5d4cd)];

  /// red color scale (dark mode)
  static const List<Color> red = [Color(0xff181111), Color(0xff1e1414), Color(0xff361519), Color(0xff49141d), Color(0xff591c24), Color(0xff6a292f), Color(0xff82393c), Color(0xffa84c4c), Color(0xffd45453), Color(0xffdc6763), Color(0xffff918c), Color(0xfff8d3d9)];

  /// ruby color scale (dark mode)
  static const List<Color> ruby = [Color(0xff181113), Color(0xff1d1517), Color(0xff35161e), Color(0xff471725), Color(0xff561f2e), Color(0xff662a39), Color(0xff7e3948), Color(0xffa64b5c), Color(0xffd45268), Color(0xffdb6474), Color(0xffff9196), Color(0xfff7d4e0)];

  /// crimson color scale (dark mode)
  static const List<Color> crimson = [Color(0xff181114), Color(0xff1e1418), Color(0xff341724), Color(0xff47162e), Color(0xff551d38), Color(0xff642944), Color(0xff7d3956), Color(0xffa34a6d), Color(0xffd74c81), Color(0xffdc5d89), Color(0xffff8fa8), Color(0xfff6d5e7)];

  /// pink color scale (dark mode)
  static const List<Color> pink = [Color(0xff181117), Color(0xff1f131c), Color(0xff32192e), Color(0xff45183b), Color(0xff522046), Color(0xff612d53), Color(0xff7a3d67), Color(0xff9c4e82), Color(0xffc64c9c), Color(0xffce5ba4), Color(0xffff88c7), Color(0xfff6d3e9)];

  /// plum color scale (dark mode)
  static const List<Color> plum = [Color(0xff171117), Color(0xff1e141f), Color(0xff311b34), Color(0xff401f45), Color(0xff4b2751), Color(0xff57325f), Color(0xff6c4376), Color(0xff8a5798), Color(0xff9f50b5), Color(0xffaa5dbf), Color(0xffdb9aee), Color(0xffefd5f2)];

  /// purple color scale (dark mode)
  static const List<Color> purple = [Color(0xff17111a), Color(0xff1d1522), Color(0xff2d1d39), Color(0xff39234c), Color(0xff432b59), Color(0xff4f3568), Color(0xff61447e), Color(0xff7d59a5), Color(0xff8551c0), Color(0xff915fca), Color(0xffcc9eff), Color(0xffe9daf8)];

  /// violet color scale (dark mode)
  static const List<Color> violet = [Color(0xff14121e), Color(0xff1a1524), Color(0xff271f41), Color(0xff312658), Color(0xff3a2e65), Color(0xff453972), Color(0xff534787), Color(0xff6658a7), Color(0xff6a57c8), Color(0xff7a67d2), Color(0xffb8a6ff), Color(0xffe1ddfb)];

  /// iris color scale (dark mode)
  static const List<Color> iris = [Color(0xff13131d), Color(0xff171624), Color(0xff212245), Color(0xff272a61), Color(0xff313370), Color(0xff3d3d7d), Color(0xff4a4a90), Color(0xff5958ac), Color(0xff5b5bcf), Color(0xff6d6ad7), Color(0xffafa9ff), Color(0xffe0dffb)];

  /// indigo color scale (dark mode)
  static const List<Color> indigo = [Color(0xff11131e), Color(0xff151725), Color(0xff1b2446), Color(0xff212e5e), Color(0xff2a3870), Color(0xff344380), Color(0xff3e4f93), Color(0xff495cac), Color(0xff4662d5), Color(0xff5a71dd), Color(0xffa1b0ff), Color(0xffd8e1fc)];

  /// blue color scale (dark mode)
  static const List<Color> blue = [Color(0xff0f151f), Color(0xff121925), Color(0xff142745), Color(0xff08325e), Color(0xff143e70), Color(0xff244c82), Color(0xff325c99), Color(0xff3d6fb8), Color(0xff3f8ef7), Color(0xff589cf8), Color(0xff7db8ff), Color(0xffc9e5fc)];

  /// cyan color scale (dark mode)
  static const List<Color> cyan = [Color(0xff0e1619), Color(0xff121b1f), Color(0xff132b35), Color(0xff103747), Color(0xff174456), Color(0xff235366), Color(0xff2f657b), Color(0xff3b7e99), Color(0xff48a0c3), Color(0xff54accc), Color(0xff72c9e2), Color(0xffc1eaf5)];

  /// teal color scale (dark mode)
  static const List<Color> teal = [Color(0xff0f1514), Color(0xff131c1b), Color(0xff162d2a), Color(0xff163a37), Color(0xff1f4743), Color(0xff295550), Color(0xff346861), Color(0xff3e7d74), Color(0xff4ca294), Color(0xff51b09e), Color(0xff63d5b7), Color(0xffbbeede)];

  /// jade color scale (dark mode)
  static const List<Color> jade = [Color(0xff0f1512), Color(0xff141c18), Color(0xff172d23), Color(0xff1a3a2d), Color(0xff224738), Color(0xff2c5546), Color(0xff386755), Color(0xff437c69), Color(0xff51a185), Color(0xff56ad8e), Color(0xff66d5a7), Color(0xffbbeed6)];

  /// green color scale (dark mode)
  static const List<Color> green = [Color(0xff101512), Color(0xff141b17), Color(0xff1a2c22), Color(0xff1d3a2a), Color(0xff254835), Color(0xff2f5640), Color(0xff3a674c), Color(0xff457a5a), Color(0xff55a271), Color(0xff5bae79), Color(0xff6fd392), Color(0xffbeefce)];

  /// grass color scale (dark mode)
  static const List<Color> grass = [Color(0xff101511), Color(0xff151a16), Color(0xff1e2a1f), Color(0xff243926), Color(0xff2d472f), Color(0xff375639), Color(0xff426643), Color(0xff4d784e), Color(0xff61a560), Color(0xff6db16d), Color(0xff88ce8a), Color(0xffcbefc6)];

  /// brown color scale (dark mode)
  static const List<Color> brown = [Color(0xff12110f), Color(0xff1b1816), Color(0xff27211d), Color(0xff312923), Color(0xff3c3129), Color(0xff4a3c31), Color(0xff5d4b3b), Color(0xff786049), Color(0xffa6815e), Color(0xffb28e6c), Color(0xffd5b698), Color(0xffefe2cd)];

  /// orange color scale (dark mode)
  static const List<Color> orange = [Color(0xff16120f), Color(0xff1d1710), Color(0xff301f0e), Color(0xff432200), Color(0xff502b04), Color(0xff603816), Color(0xff774825), Color(0xff995c33), Color(0xffe67333), Color(0xfffa823b), Color(0xffffa161), Color(0xfffae1c6)];

  /// sky color scale (dark mode)
  static const List<Color> sky = [Color(0xff0e141e), Color(0xff131a26), Color(0xff17273e), Color(0xff1b3552), Color(0xff224364), Color(0xff2b5278), Color(0xff34648e), Color(0xff3b7aaa), Color(0xff95e0fb), Color(0xffb7ecfd), Color(0xff89c5ec), Color(0xffccf1fd)];

  /// mint color scale (dark mode)
  static const List<Color> mint = [Color(0xff0f1515), Color(0xff111b1b), Color(0xff142b2b), Color(0xff113938), Color(0xff1b4643), Color(0xff275550), Color(0xff35675f), Color(0xff427d70), Color(0xff9ee8d5), Color(0xffb9f3e5), Color(0xff7bd2bb), Color(0xffcef4e2)];

  /// lime color scale (dark mode)
  static const List<Color> lime = [Color(0xff11130c), Color(0xff161a11), Color(0xff212919), Color(0xff2c3720), Color(0xff364427), Color(0xff42522e), Color(0xff4e6237), Color(0xff5d7440), Color(0xffc7ed77), Color(0xffddfe84), Color(0xffc5e47c), Color(0xffe7f6c0)];

  /// yellow color scale (dark mode)
  static const List<Color> yellow = [Color(0xff14120c), Color(0xff1a1810), Color(0xff2b230a), Color(0xff352b00), Color(0xff413500), Color(0xff4f4312), Color(0xff635422), Color(0xff7f6b2e), Color(0xffffeb38), Color(0xffffff74), Color(0xfff2e264), Color(0xfff5eeba)];

  /// amber color scale (dark mode)
  static const List<Color> amber = [Color(0xff15120d), Color(0xff1c1810), Color(0xff2d210c), Color(0xff3d2800), Color(0xff4a3100), Color(0xff583e13), Color(0xff6c5024), Color(0xff886630), Color(0xffffc442), Color(0xffffde26), Color(0xffffcc4a), Color(0xfffbe8b9)];

}
