builders:
  flywind:
    import: "package:flywind/builder.dart"
    builder_factories: ["flywindBuilder"]
    build_extensions: { "flywind.yaml": ["lib/tokens/tokens.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: []

targets:
  $default:
    builders:
      flywind:
        enabled: true
