builders:
  flywind_yaml:
    import: "package:flywind/builder.dart"
    builder_factories: ["flywindYamlBuilder"]
    build_extensions: { "lib/fly/flywind.yaml": ["lib/fly/tokens/tokens.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: []
    required_inputs: ["lib/fly/flywind.yaml"]

targets:
  $default:
    builders:
      flywind:flywind_yaml:
        enabled: true
