targets:
  $default:
    builders:
      flywind:flywindBuilder:
        enabled: true
        build_extensions: { ".dart": [".flywind.g.part"] }
        build_to: cache
        applies_builders: ["source_gen:combining_builder"]
