// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//
// Generated on: 2025-09-21T10:11:10.546412

/// Border radius scale class with type-safe access to radius values
class FlyBorderRadius {
  const FlyBorderRadius({
    required this.none,
    required this.sm,
    required this.md,
    required this.lg,
    required this.xl,
    required this.xl2,
    required this.xl3,
    required this.full,
    required this.defaultValue,
    this.customBorderRadius = const {},
  });

  final String none;
  final String sm;
  final String md;
  final String lg;
  final String xl;
  final String xl2;
  final String xl3;
  final String full;
  final String defaultValue;
  final Map<String, String> customBorderRadius;

  /// Get all values as a map
  Map<String, String> get values => {
    'none': none,
    'sm': sm,
    'md': md,
    'lg': lg,
    'xl': xl,
    '2xl': xl2,
    '3xl': xl3,
    'full': full,
    '': defaultValue,
    ...customBorderRadius,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customBorderRadius[key];

  /// Get the actual double value for a given key
  double? getValue(String key) {
    final stringValue = values[key];
    if (stringValue == null) return null;
    return double.tryParse(stringValue);
  }

  /// Create a copy with updated values
  FlyBorderRadius copyWith({
    String? none,
    String? sm,
    String? md,
    String? lg,
    String? xl,
    String? xl2,
    String? xl3,
    String? full,
    String? defaultValue,
    Map<String, String>? customBorderRadius,
  }) {
    return FlyBorderRadius(
      none: none ?? this.none,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      full: full ?? this.full,
      defaultValue: defaultValue ?? this.defaultValue,
      customBorderRadius: customBorderRadius ?? this.customBorderRadius,
    );
  }

  /// Default FlyBorderRadius instance
  static const FlyBorderRadius defaultBorderRadius = FlyBorderRadius(
    none: '0',
    sm: '2',
    md: '6',
    lg: '8',
    xl: '12',
    xl2: '16',
    xl3: '24',
    full: '9999',
    defaultValue: '4',
  );
}
