// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by generate.dart
// To regenerate, run: dart generate/generate.dart
//

import '../core/token.dart';

/// Breakpoint values for responsive design
class FlyBreakpointToken implements FlyToken<double> {
  const FlyBreakpointToken({
    required this.sm,
    required this.md,
    required this.lg,
    required this.xl,
    required this.xl2,
    this.extras = const {},
  });

  /// sm Breakpoint values for responsive design
  final double sm;
  /// md Breakpoint values for responsive design
  final double md;
  /// lg Breakpoint values for responsive design
  final double lg;
  /// xl Breakpoint values for responsive design
  final double xl;
  /// 2xl Breakpoint values for responsive design
  final double xl2;

  /// Additional custom values
  final Map<String, double> extras;

  /// All values in a single map for easier iteration
  Map<String, double> get _allValues => {
    'sm': sm,
    'md': md,
    'lg': lg,
    'xl': xl,
    'xl2': xl2,
    ...extras,
  };

  /// Access value by key (canonical or extra)
  @override
  double? operator[](String key) => _allValues[key];

  /// Get all available keys (canonical + extras)
  @override
  Iterable<String> get keys => _allValues.keys;

  /// Put a new value for the given key
  @override
  FlyBreakpointToken put(String key, double value) {
    switch (key) {
      case 'sm':
        return copyWith(sm: value);
      case 'md':
        return copyWith(md: value);
      case 'lg':
        return copyWith(lg: value);
      case 'xl':
        return copyWith(xl: value);
      case 'xl2':
        return copyWith(xl2: value);
      default:
        final newExtras = Map<String, double>.from(extras);
        newExtras[key] = value;
        return copyWith(extras: newExtras);
    }
  }

  /// Merge another token into this one (right side wins)
  @override
  FlyBreakpointToken merge(FlyToken<double> other) {
    if (other is! FlyBreakpointToken) return this;
    
    return copyWith(
      sm: other.sm,
      md: other.md,
      lg: other.lg,
      xl: other.xl,
      xl2: other.xl2,
      extras: {...extras, ...other.extras},
    );
  }

  /// Create a copy with updated values
  FlyBreakpointToken copyWith({
    double? sm,
    double? md,
    double? lg,
    double? xl,
    double? xl2,
    Map<String, double>? extras,
  }) {
    return FlyBreakpointToken(
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      extras: extras ?? this.extras,
    );
  }

  /// Linear interpolation between two tokens
  FlyBreakpointToken lerp(FlyBreakpointToken other, double t) {
    final result = <String, double>{};
    final allKeys = {..._allValues.keys, ...other._allValues.keys};
    
    for (final key in allKeys) {
      final valueA = _allValues[key];
      final valueB = other._allValues[key];
      final numA = valueA ?? 0.0;
      final numB = valueB ?? 0.0;
      result[key] = numA + (numB - numA) * t;
    }
    
    return FlyBreakpointToken(
      sm: result['sm']!,
      md: result['md']!,
      lg: result['lg']!,
      xl: result['xl']!,
      xl2: result['xl2']!,
      extras: Map.fromEntries(result.entries.where((e) => !['sm', 'md', 'lg', 'xl', 'xl2'].contains(e.key))),
    );
  }

  /// Create default values
  static FlyBreakpointToken defaultBreakpoint() {
    return const FlyBreakpointToken(
      sm: 640.0,
      md: 768.0,
      lg: 1024.0,
      xl: 1280.0,
      xl2: 1536.0,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is FlyBreakpointToken && _allValues.toString() == other._allValues.toString();
  }

  @override
  int get hashCode => _allValues.hashCode;
}
