// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//

/// Container size class with type-safe access to container values
class FlyContainers {
  const FlyContainers({
    required this.xs3,
    required this.xs2,
    required this.xs,
    required this.sm,
    required this.md,
    required this.lg,
    required this.xl,
    required this.xl2,
    required this.xl3,
    required this.xl4,
    required this.xl5,
    required this.xl6,
    required this.xl7,
    this.customContainers = const {},
  });

  final String xs3;
  final String xs2;
  final String xs;
  final String sm;
  final String md;
  final String lg;
  final String xl;
  final String xl2;
  final String xl3;
  final String xl4;
  final String xl5;
  final String xl6;
  final String xl7;
  final Map<String, String> customContainers;

  /// Get all values as a map
  Map<String, String> get values => {
    'xs3': xs3,
    'xs2': xs2,
    'xs': xs,
    'sm': sm,
    'md': md,
    'lg': lg,
    'xl': xl,
    'xl2': xl2,
    'xl3': xl3,
    'xl4': xl4,
    'xl5': xl5,
    'xl6': xl6,
    'xl7': xl7,
    ...customContainers,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customContainers[key];

  /// Create a copy with updated values
  FlyContainers copyWith({
    String? xs3,
    String? xs2,
    String? xs,
    String? sm,
    String? md,
    String? lg,
    String? xl,
    String? xl2,
    String? xl3,
    String? xl4,
    String? xl5,
    String? xl6,
    String? xl7,
    Map<String, String>? customContainers,
  }) {
    return FlyContainers(
      xs3: xs3 ?? this.xs3,
      xs2: xs2 ?? this.xs2,
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      xl4: xl4 ?? this.xl4,
      xl5: xl5 ?? this.xl5,
      xl6: xl6 ?? this.xl6,
      xl7: xl7 ?? this.xl7,
      customContainers: customContainers ?? this.customContainers,
    );
  }

  /// Default FlyContainers instance
  static const FlyContainers defaultContainers = FlyContainers(
    xs3: '256',
    xs2: '288',
    xs: '320',
    sm: '384',
    md: '448',
    lg: '512',
    xl: '576',
    xl2: '672',
    xl3: '768',
    xl4: '896',
    xl5: '1024',
    xl6: '1152',
    xl7: '1280',
  );
}

/// Extension on FlyContainers to easily override specific values
extension FlyContainersExtension on FlyContainers {
  /// Create a new FlyContainers instance with specific value overrides
  FlyContainers copyWith({
    String? xs3,
    String? xs2,
    String? xs,
    String? sm,
    String? md,
    String? lg,
    String? xl,
    String? xl2,
    String? xl3,
    String? xl4,
    String? xl5,
    String? xl6,
    String? xl7,
    Map<String, String>? customContainers,
  }) {
    return FlyContainers(
      xs3: xs3 ?? this.xs3,
      xs2: xs2 ?? this.xs2,
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      xl4: xl4 ?? this.xl4,
      xl5: xl5 ?? this.xl5,
      xl6: xl6 ?? this.xl6,
      xl7: xl7 ?? this.xl7,
      customContainers: customContainers ?? this.customContainers,
    );
  }
}
