// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//
// Generated on: 2025-09-21T11:33:46.074556

/// Drop shadow class with type-safe access to drop shadow values
class FlyDropShadows {
  const FlyDropShadows({
    required this.xs,
    required this.sm,
    required this.md,
    required this.lg,
    required this.xl,
    required this.xl2,
    this.customDropShadows = const {},
  });

  final String xs;
  final String sm;
  final String md;
  final String lg;
  final String xl;
  final String xl2;
  final Map<String, String> customDropShadows;

  /// Get all values as a map
  Map<String, String> get values => {
    'xs': xs,
    'sm': sm,
    'md': md,
    'lg': lg,
    'xl': xl,
    'xl2': xl2,
    ...customDropShadows,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customDropShadows[key];

  /// Create a copy with updated values
  FlyDropShadows copyWith({
    String? xs,
    String? sm,
    String? md,
    String? lg,
    String? xl,
    String? xl2,
    Map<String, String>? customDropShadows,
  }) {
    return FlyDropShadows(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      customDropShadows: customDropShadows ?? this.customDropShadows,
    );
  }

  /// Default FlyDropShadows instance
  static const FlyDropShadows defaultDropShadows = FlyDropShadows(
    xs: 'BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.05), offset: Offset(0.0, 1.0), blurRadius: 1.0, spreadRadius: 0.0)',
    sm: 'BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.15), offset: Offset(0.0, 1.0), blurRadius: 2.0, spreadRadius: 0.0)',
    md: 'BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.12), offset: Offset(0.0, 3.0), blurRadius: 3.0, spreadRadius: 0.0)',
    lg: 'BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.15), offset: Offset(0.0, 4.0), blurRadius: 4.0, spreadRadius: 0.0)',
    xl: 'BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 9.0), blurRadius: 7.0, spreadRadius: 0.0)',
    xl2: 'BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.15), offset: Offset(0.0, 25.0), blurRadius: 25.0, spreadRadius: 0.0)',
  );
}

/// Extension on FlyDropShadows to easily override specific values
extension FlyDropShadowsExtension on FlyDropShadows {
  /// Create a new FlyDropShadows instance with specific value overrides
  FlyDropShadows copyWith({
    String? xs,
    String? sm,
    String? md,
    String? lg,
    String? xl,
    String? xl2,
    Map<String, String>? customDropShadows,
  }) {
    return FlyDropShadows(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      customDropShadows: customDropShadows ?? this.customDropShadows,
    );
  }
}
