// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//
// Generated on: 2025-09-21T11:33:46.077713

/// Font family class with type-safe access to font family values
class FlyFontFamilies {
  const FlyFontFamilies({
    required this.sans,
    required this.serif,
    required this.mono,
    this.customFontFamilies = const {},
  });

  final String sans;
  final String serif;
  final String mono;
  final Map<String, String> customFontFamilies;

  /// Get all values as a map
  Map<String, String> get values => {
    'sans': sans,
    'serif': serif,
    'mono': mono,
    ...customFontFamilies,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customFontFamilies[key];

  /// Create a copy with updated values
  FlyFontFamilies copyWith({
    String? sans,
    String? serif,
    String? mono,
    Map<String, String>? customFontFamilies,
  }) {
    return FlyFontFamilies(
      sans: sans ?? this.sans,
      serif: serif ?? this.serif,
      mono: mono ?? this.mono,
      customFontFamilies: customFontFamilies ?? this.customFontFamilies,
    );
  }

  /// Default FlyFontFamilies instance
  static const FlyFontFamilies defaultFontFamilies = FlyFontFamilies(
    sans: '["ui-sans-serif", "system-ui", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"]',
    serif: '["ui-serif", "Georgia", "Cambria", "Times New Roman", "Times", "serif"]',
    mono: '["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"]',
  );
}

/// Extension on FlyFontFamilies to easily override specific values
extension FlyFontFamiliesExtension on FlyFontFamilies {
  /// Create a new FlyFontFamilies instance with specific value overrides
  FlyFontFamilies copyWith({
    String? sans,
    String? serif,
    String? mono,
    Map<String, String>? customFontFamilies,
  }) {
    return FlyFontFamilies(
      sans: sans ?? this.sans,
      serif: serif ?? this.serif,
      mono: mono ?? this.mono,
      customFontFamilies: customFontFamilies ?? this.customFontFamilies,
    );
  }
}
