// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//

/// Line height class with type-safe access to line height values
class FlyLineHeights {
  const FlyLineHeights({
    required this.tight,
    required this.snug,
    required this.normal,
    required this.relaxed,
    required this.loose,
    this.customLineHeights = const {},
  });

  final String tight;
  final String snug;
  final String normal;
  final String relaxed;
  final String loose;
  final Map<String, String> customLineHeights;

  /// Get all values as a map
  Map<String, String> get values => {
    'tight': tight,
    'snug': snug,
    'normal': normal,
    'relaxed': relaxed,
    'loose': loose,
    ...customLineHeights,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customLineHeights[key];

  /// Create a copy with updated values
  FlyLineHeights copyWith({
    String? tight,
    String? snug,
    String? normal,
    String? relaxed,
    String? loose,
    Map<String, String>? customLineHeights,
  }) {
    return FlyLineHeights(
      tight: tight ?? this.tight,
      snug: snug ?? this.snug,
      normal: normal ?? this.normal,
      relaxed: relaxed ?? this.relaxed,
      loose: loose ?? this.loose,
      customLineHeights: customLineHeights ?? this.customLineHeights,
    );
  }

  /// Default FlyLineHeights instance
  static const FlyLineHeights defaultLineHeights = FlyLineHeights(
    tight: '1.25',
    snug: '1.375',
    normal: '1.5',
    relaxed: '1.625',
    loose: '2',
  );
}

/// Extension on FlyLineHeights to easily override specific values
extension FlyLineHeightsExtension on FlyLineHeights {
  /// Create a new FlyLineHeights instance with specific value overrides
  FlyLineHeights copyWith({
    String? tight,
    String? snug,
    String? normal,
    String? relaxed,
    String? loose,
    Map<String, String>? customLineHeights,
  }) {
    return FlyLineHeights(
      tight: tight ?? this.tight,
      snug: snug ?? this.snug,
      normal: normal ?? this.normal,
      relaxed: relaxed ?? this.relaxed,
      loose: loose ?? this.loose,
      customLineHeights: customLineHeights ?? this.customLineHeights,
    );
  }
}
