// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by generate.dart
// To regenerate, run: dart generate/generate.dart
//

import '../src/theme.dart';

/// Perspective transform values
class FlyPerspectiveToken implements FlyToken<double> {
  const FlyPerspectiveToken({
    required this.dramatic,
    required this.near,
    required this.normal,
    required this.midrange,
    required this.distant,
    this.extras = const {},
  });

  /// dramatic Perspective transform values
  final double dramatic;
  /// near Perspective transform values
  final double near;
  /// normal Perspective transform values
  final double normal;
  /// midrange Perspective transform values
  final double midrange;
  /// distant Perspective transform values
  final double distant;

  /// Additional custom values
  final Map<String, double> extras;

  /// All values in a single map for easier iteration
  Map<String, double> get _allValues => {
    'dramatic': dramatic,
    'near': near,
    'normal': normal,
    'midrange': midrange,
    'distant': distant,
    ...extras,
  };

  /// Access value by key (canonical or extra)
  @override
  double? operator[](String key) => _allValues[key];

  /// Get all available keys (canonical + extras)
  @override
  Iterable<String> get keys => _allValues.keys;

  /// Put a new value for the given key
  @override
  FlyPerspectiveToken put(String key, double value) {
    switch (key) {
      case 'dramatic':
        return copyWith(dramatic: value);
      case 'near':
        return copyWith(near: value);
      case 'normal':
        return copyWith(normal: value);
      case 'midrange':
        return copyWith(midrange: value);
      case 'distant':
        return copyWith(distant: value);
      default:
        final newExtras = Map<String, double>.from(extras);
        newExtras[key] = value;
        return copyWith(extras: newExtras);
    }
  }

  /// Merge another token into this one (right side wins)
  @override
  FlyPerspectiveToken merge(FlyToken<double> other) {
    if (other is! FlyPerspectiveToken) return this;
    
    return copyWith(
      dramatic: other.dramatic,
      near: other.near,
      normal: other.normal,
      midrange: other.midrange,
      distant: other.distant,
      extras: {...extras, ...other.extras},
    );
  }

  /// Create a copy with updated values
  FlyPerspectiveToken copyWith({
    double? dramatic,
    double? near,
    double? normal,
    double? midrange,
    double? distant,
    Map<String, double>? extras,
  }) {
    return FlyPerspectiveToken(
      dramatic: dramatic ?? this.dramatic,
      near: near ?? this.near,
      normal: normal ?? this.normal,
      midrange: midrange ?? this.midrange,
      distant: distant ?? this.distant,
      extras: extras ?? this.extras,
    );
  }

  /// Linear interpolation between two tokens
  FlyPerspectiveToken lerp(FlyPerspectiveToken other, double t) {
    final result = <String, double>{};
    final allKeys = {..._allValues.keys, ...other._allValues.keys};
    
    for (final key in allKeys) {
      final valueA = _allValues[key];
      final valueB = other._allValues[key];
      final numA = valueA ?? 0.0;
      final numB = valueB ?? 0.0;
      result[key] = numA + (numB - numA) * t;
    }
    
    return FlyPerspectiveToken(
      dramatic: result['dramatic']!,
      near: result['near']!,
      normal: result['normal']!,
      midrange: result['midrange']!,
      distant: result['distant']!,
      extras: Map.fromEntries(result.entries.where((e) => !['dramatic', 'near', 'normal', 'midrange', 'distant'].contains(e.key))),
    );
  }

  /// Create default values
  static FlyPerspectiveToken defaultPerspective() {
    return const FlyPerspectiveToken(
      dramatic: 100.0,
      near: 300.0,
      normal: 500.0,
      midrange: 800.0,
      distant: 1200.0,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is FlyPerspectiveToken && _allValues.toString() == other._allValues.toString();
  }

  @override
  int get hashCode => _allValues.hashCode;
}
