// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//
// Generated on: 2025-09-21T11:33:46.073632

/// Perspective class with type-safe access to perspective values
class FlyPerspectives {
  const FlyPerspectives({
    required this.dramatic,
    required this.near,
    required this.normal,
    required this.midrange,
    required this.distant,
    this.customPerspectives = const {},
  });

  final String dramatic;
  final String near;
  final String normal;
  final String midrange;
  final String distant;
  final Map<String, String> customPerspectives;

  /// Get all values as a map
  Map<String, String> get values => {
    'dramatic': dramatic,
    'near': near,
    'normal': normal,
    'midrange': midrange,
    'distant': distant,
    ...customPerspectives,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customPerspectives[key];

  /// Create a copy with updated values
  FlyPerspectives copyWith({
    String? dramatic,
    String? near,
    String? normal,
    String? midrange,
    String? distant,
    Map<String, String>? customPerspectives,
  }) {
    return FlyPerspectives(
      dramatic: dramatic ?? this.dramatic,
      near: near ?? this.near,
      normal: normal ?? this.normal,
      midrange: midrange ?? this.midrange,
      distant: distant ?? this.distant,
      customPerspectives: customPerspectives ?? this.customPerspectives,
    );
  }

  /// Default FlyPerspectives instance
  static const FlyPerspectives defaultPerspectives = FlyPerspectives(
    dramatic: '100',
    near: '300',
    normal: '500',
    midrange: '800',
    distant: '1200',
  );
}

/// Extension on FlyPerspectives to easily override specific values
extension FlyPerspectivesExtension on FlyPerspectives {
  /// Create a new FlyPerspectives instance with specific value overrides
  FlyPerspectives copyWith({
    String? dramatic,
    String? near,
    String? normal,
    String? midrange,
    String? distant,
    Map<String, String>? customPerspectives,
  }) {
    return FlyPerspectives(
      dramatic: dramatic ?? this.dramatic,
      near: near ?? this.near,
      normal: normal ?? this.normal,
      midrange: midrange ?? this.midrange,
      distant: distant ?? this.distant,
      customPerspectives: customPerspectives ?? this.customPerspectives,
    );
  }
}
