// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//

/// Border radius class with type-safe access to border radius values
class FlyBorderRadius {
  const FlyBorderRadius({
    required this.xs,
    required this.sm,
    required this.md,
    required this.lg,
    required this.xl,
    required this.xl2,
    required this.xl3,
    required this.xl4,
    this.customBorderRadius = const {},
  });

  final String xs;
  final String sm;
  final String md;
  final String lg;
  final String xl;
  final String xl2;
  final String xl3;
  final String xl4;
  final Map<String, String> customBorderRadius;

  /// Get all values as a map
  Map<String, String> get values => {
    'xs': xs,
    'sm': sm,
    'md': md,
    'lg': lg,
    'xl': xl,
    'xl2': xl2,
    'xl3': xl3,
    'xl4': xl4,
    ...customBorderRadius,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customBorderRadius[key];

  /// Create a copy with updated values
  FlyBorderRadius copyWith({
    String? xs,
    String? sm,
    String? md,
    String? lg,
    String? xl,
    String? xl2,
    String? xl3,
    String? xl4,
    Map<String, String>? customBorderRadius,
  }) {
    return FlyBorderRadius(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      xl4: xl4 ?? this.xl4,
      customBorderRadius: customBorderRadius ?? this.customBorderRadius,
    );
  }

  /// Default FlyBorderRadius instance
  static const FlyBorderRadius defaultBorderRadius = FlyBorderRadius(
    xs: '2',
    sm: '4',
    md: '6',
    lg: '8',
    xl: '12',
    xl2: '16',
    xl3: '24',
    xl4: '32',
  );
}

/// Extension on FlyBorderRadius to easily override specific values
extension FlyBorderRadiusExtension on FlyBorderRadius {
  /// Create a new FlyBorderRadius instance with specific value overrides
  FlyBorderRadius copyWith({
    String? xs,
    String? sm,
    String? md,
    String? lg,
    String? xl,
    String? xl2,
    String? xl3,
    String? xl4,
    Map<String, String>? customBorderRadius,
  }) {
    return FlyBorderRadius(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      xl4: xl4 ?? this.xl4,
      customBorderRadius: customBorderRadius ?? this.customBorderRadius,
    );
  }
}
