// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//

/// Shadow class with type-safe access to shadow values
class FlyShadows {
  const FlyShadows({
    required this.xs2,
    required this.xs,
    required this.sm,
    required this.md,
    required this.lg,
    required this.xl,
    required this.xl2,
    required this.inner,
    this.customShadows = const {},
  });

  final String xs2;
  final String xs;
  final String sm;
  final String md;
  final String lg;
  final String xl;
  final String xl2;
  final String inner;
  final Map<String, String> customShadows;

  /// Get all values as a map
  Map<String, String> get values => {
    'xs2': xs2,
    'xs': xs,
    'sm': sm,
    'md': md,
    'lg': lg,
    'xl': xl,
    'xl2': xl2,
    'inner': inner,
    ...customShadows,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customShadows[key];

  /// Create a copy with updated values
  FlyShadows copyWith({
    String? xs2,
    String? xs,
    String? sm,
    String? md,
    String? lg,
    String? xl,
    String? xl2,
    String? inner,
    Map<String, String>? customShadows,
  }) {
    return FlyShadows(
      xs2: xs2 ?? this.xs2,
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      inner: inner ?? this.inner,
      customShadows: customShadows ?? this.customShadows,
    );
  }

  /// Default FlyShadows instance
  static const FlyShadows defaultShadows = FlyShadows(
    xs2: 'BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.05), offset: Offset(0.0, 1.0), blurRadius: 0.0, spreadRadius: 0.0)',
    xs: 'BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.05), offset: Offset(0.0, 1.0), blurRadius: 2.0, spreadRadius: 0.0)',
    sm: '[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 1.0), blurRadius: 3.0, spreadRadius: 0.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 1.0), blurRadius: 2.0, spreadRadius: -1.0)]',
    md: '[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 4.0), blurRadius: 6.0, spreadRadius: -1.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 2.0), blurRadius: 4.0, spreadRadius: -2.0)]',
    lg: '[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 10.0), blurRadius: 15.0, spreadRadius: -3.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 4.0), blurRadius: 6.0, spreadRadius: -4.0)]',
    xl: '[BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 20.0), blurRadius: 25.0, spreadRadius: -5.0), BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 8.0), blurRadius: 10.0, spreadRadius: -6.0)]',
    xl2: 'BoxShadow(color: Color.fromRGBO(0, 0, 0, 0.25), offset: Offset(0.0, 25.0), blurRadius: 50.0, spreadRadius: -12.0)',
    inner: 'InsetShadow(color: Colors.black.withOpacity(0.1), blurRadius: 4, offset: Offset(0, 2))',
  );
}

/// Extension on FlyShadows to easily override specific values
extension FlyShadowsExtension on FlyShadows {
  /// Create a new FlyShadows instance with specific value overrides
  FlyShadows copyWith({
    String? xs2,
    String? xs,
    String? sm,
    String? md,
    String? lg,
    String? xl,
    String? xl2,
    String? inner,
    Map<String, String>? customShadows,
  }) {
    return FlyShadows(
      xs2: xs2 ?? this.xs2,
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      inner: inner ?? this.inner,
      customShadows: customShadows ?? this.customShadows,
    );
  }
}
