// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//
// Generated on: 2025-09-21T10:11:10.542225

/// Spacing scale class with type-safe access to spacing values
class FlySpacing {
  const FlySpacing({
    required this.s0,
    required this.s1,
    required this.s2,
    required this.s3,
    required this.s4,
    required this.s5,
    required this.s6,
    required this.s7,
    required this.s8,
    required this.s9,
    required this.s10,
    required this.s11,
    required this.s12,
    this.customSpacing = const {},
  });

  final String s0;
  final String s1;
  final String s2;
  final String s3;
  final String s4;
  final String s5;
  final String s6;
  final String s7;
  final String s8;
  final String s9;
  final String s10;
  final String s11;
  final String s12;
  final Map<int, String> customSpacing;

  /// Get all values as a map
  Map<int, String> get values => {
    0: s0,
    1: s1,
    2: s2,
    3: s3,
    4: s4,
    5: s5,
    6: s6,
    7: s7,
    8: s8,
    9: s9,
    10: s10,
    11: s11,
    12: s12,
  };

  /// Access values by index
  String? operator [](int index) => values[index];

  /// Create a copy with updated values
  FlySpacing copyWith({
    String? s0,
    String? s1,
    String? s2,
    String? s3,
    String? s4,
    String? s5,
    String? s6,
    String? s7,
    String? s8,
    String? s9,
    String? s10,
    String? s11,
    String? s12,
    Map<int, String>? customSpacing,
  }) {
    return FlySpacing(
      s0: s0 ?? this.s0,
      s1: s1 ?? this.s1,
      s2: s2 ?? this.s2,
      s3: s3 ?? this.s3,
      s4: s4 ?? this.s4,
      s5: s5 ?? this.s5,
      s6: s6 ?? this.s6,
      s7: s7 ?? this.s7,
      s8: s8 ?? this.s8,
      s9: s9 ?? this.s9,
      s10: s10 ?? this.s10,
      s11: s11 ?? this.s11,
      s12: s12 ?? this.s12,
      customSpacing: customSpacing ?? this.customSpacing,
    );
  }

  /// Default FlySpacing instance
  static const FlySpacing defaultSpacing = FlySpacing(
    s0: '0',
    s1: '4',
    s2: '8',
    s3: '12',
    s4: '16',
    s5: '20',
    s6: '24',
    s7: '28',
    s8: '32',
    s9: '36',
    s10: '40',
    s11: '44',
    s12: '48',
  );
}
