// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//
// Generated on: 2025-09-21T11:33:46.074991

/// Spacing class with type-safe access to spacing values
class FlySpacing {
  const FlySpacing({
    required this.base,
    required this.xs,
    required this.sm,
    required this.md,
    required this.lg,
    required this.xl,
    this.customSpacing = const {},
  });

  final String base;
  final String xs;
  final String sm;
  final String md;
  final String lg;
  final String xl;
  final Map<String, String> customSpacing;

  /// Get all values as a map
  Map<String, String> get values => {
    'base': base,
    'xs': xs,
    'sm': sm,
    'md': md,
    'lg': lg,
    'xl': xl,
    ...customSpacing,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customSpacing[key];

  /// Create a copy with updated values
  FlySpacing copyWith({
    String? base,
    String? xs,
    String? sm,
    String? md,
    String? lg,
    String? xl,
    Map<String, String>? customSpacing,
  }) {
    return FlySpacing(
      base: base ?? this.base,
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      customSpacing: customSpacing ?? this.customSpacing,
    );
  }

  /// Default FlySpacing instance
  static const FlySpacing defaultSpacing = FlySpacing(
    base: '4',
    xs: '2',
    sm: '4',
    md: '8',
    lg: '16',
    xl: '32',
  );
}

/// Extension on FlySpacing to easily override specific values
extension FlySpacingExtension on FlySpacing {
  /// Create a new FlySpacing instance with specific value overrides
  FlySpacing copyWith({
    String? base,
    String? xs,
    String? sm,
    String? md,
    String? lg,
    String? xl,
    Map<String, String>? customSpacing,
  }) {
    return FlySpacing(
      base: base ?? this.base,
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      customSpacing: customSpacing ?? this.customSpacing,
    );
  }
}
