// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by generate.dart
// To regenerate, run: dart generate/generate.dart
//

import '../src/theme.dart';

/// Spacing values for margins and padding
class FlySpacingToken implements FlyToken<double> {
  const FlySpacingToken({
    required this.base,
    this.extras = const {},
  });

  /// base Spacing values for margins and padding
  final double base;

  /// Additional custom values
  final Map<String, double> extras;

  /// All values in a single map for easier iteration
  Map<String, double> get _allValues => {
    'base': base,
    ...extras,
  };

  /// Access value by key (canonical or extra)
  @override
  double? operator[](String key) => _allValues[key];

  /// Get all available keys (canonical + extras)
  @override
  Iterable<String> get keys => _allValues.keys;

  /// Put a new value for the given key
  @override
  FlySpacingToken put(String key, double value) {
    switch (key) {
      case 'base':
        return copyWith(base: value);
      default:
        final newExtras = Map<String, double>.from(extras);
        newExtras[key] = value;
        return copyWith(extras: newExtras);
    }
  }

  /// Merge another token into this one (right side wins)
  @override
  FlySpacingToken merge(FlyToken<double> other) {
    if (other is! FlySpacingToken) return this;
    
    return copyWith(
      base: other.base,
      extras: {...extras, ...other.extras},
    );
  }

  /// Create a copy with updated values
  FlySpacingToken copyWith({
    double? base,
    Map<String, double>? extras,
  }) {
    return FlySpacingToken(
      base: base ?? this.base,
      extras: extras ?? this.extras,
    );
  }

  /// Linear interpolation between two tokens
  FlySpacingToken lerp(FlySpacingToken other, double t) {
    final result = <String, double>{};
    final allKeys = {..._allValues.keys, ...other._allValues.keys};
    
    for (final key in allKeys) {
      final valueA = _allValues[key];
      final valueB = other._allValues[key];
      final numA = valueA ?? 0.0;
      final numB = valueB ?? 0.0;
      result[key] = numA + (numB - numA) * t;
    }
    
    return FlySpacingToken(
      base: result['base']!,
      extras: Map.fromEntries(result.entries.where((e) => !['base'].contains(e.key))),
    );
  }

  /// Create default values
  static FlySpacingToken defaultSpacing() {
    return const FlySpacingToken(
      base: 4.0,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is FlySpacingToken && _allValues.toString() == other._allValues.toString();
  }

  @override
  int get hashCode => _allValues.hashCode;
}
