// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by generate.dart
// To regenerate, run: dart generate/generate.dart
//

import '../core/token.dart';

/// Text line height values
class FlyTextLineHeightToken implements FlyToken<double> {
  const FlyTextLineHeightToken({
    required this.xs,
    required this.sm,
    required this.base,
    required this.lg,
    required this.xl,
    required this.xl2,
    required this.xl3,
    required this.xl4,
    required this.xl5,
    required this.xl6,
    required this.xl7,
    required this.xl8,
    required this.xl9,
    this.extras = const {},
  });

  /// xs Text line height values
  final double xs;
  /// sm Text line height values
  final double sm;
  /// base Text line height values
  final double base;
  /// lg Text line height values
  final double lg;
  /// xl Text line height values
  final double xl;
  /// 2xl Text line height values
  final double xl2;
  /// 3xl Text line height values
  final double xl3;
  /// 4xl Text line height values
  final double xl4;
  /// 5xl Text line height values
  final double xl5;
  /// 6xl Text line height values
  final double xl6;
  /// 7xl Text line height values
  final double xl7;
  /// 8xl Text line height values
  final double xl8;
  /// 9xl Text line height values
  final double xl9;

  /// Additional custom values
  final Map<String, double> extras;

  /// All values in a single map for easier iteration
  Map<String, double> get _allValues => {
    'xs': xs,
    'sm': sm,
    'base': base,
    'lg': lg,
    'xl': xl,
    'xl2': xl2,
    'xl3': xl3,
    'xl4': xl4,
    'xl5': xl5,
    'xl6': xl6,
    'xl7': xl7,
    'xl8': xl8,
    'xl9': xl9,
    ...extras,
  };

  /// Access value by key (canonical or extra)
  @override
  double? operator[](String key) => _allValues[key];

  /// Get all available keys (canonical + extras)
  @override
  Iterable<String> get keys => _allValues.keys;

  /// Put a new value for the given key
  @override
  FlyTextLineHeightToken put(String key, double value) {
    switch (key) {
      case 'xs':
        return copyWith(xs: value);
      case 'sm':
        return copyWith(sm: value);
      case 'base':
        return copyWith(base: value);
      case 'lg':
        return copyWith(lg: value);
      case 'xl':
        return copyWith(xl: value);
      case 'xl2':
        return copyWith(xl2: value);
      case 'xl3':
        return copyWith(xl3: value);
      case 'xl4':
        return copyWith(xl4: value);
      case 'xl5':
        return copyWith(xl5: value);
      case 'xl6':
        return copyWith(xl6: value);
      case 'xl7':
        return copyWith(xl7: value);
      case 'xl8':
        return copyWith(xl8: value);
      case 'xl9':
        return copyWith(xl9: value);
      default:
        final newExtras = Map<String, double>.from(extras);
        newExtras[key] = value;
        return copyWith(extras: newExtras);
    }
  }

  /// Merge another token into this one (right side wins)
  @override
  FlyTextLineHeightToken merge(FlyToken<double> other) {
    if (other is! FlyTextLineHeightToken) return this;
    
    return copyWith(
      xs: other.xs,
      sm: other.sm,
      base: other.base,
      lg: other.lg,
      xl: other.xl,
      xl2: other.xl2,
      xl3: other.xl3,
      xl4: other.xl4,
      xl5: other.xl5,
      xl6: other.xl6,
      xl7: other.xl7,
      xl8: other.xl8,
      xl9: other.xl9,
      extras: {...extras, ...other.extras},
    );
  }

  /// Create a copy with updated values
  FlyTextLineHeightToken copyWith({
    double? xs,
    double? sm,
    double? base,
    double? lg,
    double? xl,
    double? xl2,
    double? xl3,
    double? xl4,
    double? xl5,
    double? xl6,
    double? xl7,
    double? xl8,
    double? xl9,
    Map<String, double>? extras,
  }) {
    return FlyTextLineHeightToken(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      base: base ?? this.base,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      xl4: xl4 ?? this.xl4,
      xl5: xl5 ?? this.xl5,
      xl6: xl6 ?? this.xl6,
      xl7: xl7 ?? this.xl7,
      xl8: xl8 ?? this.xl8,
      xl9: xl9 ?? this.xl9,
      extras: extras ?? this.extras,
    );
  }

  /// Linear interpolation between two tokens
  FlyTextLineHeightToken lerp(FlyTextLineHeightToken other, double t) {
    final result = <String, double>{};
    final allKeys = {..._allValues.keys, ...other._allValues.keys};
    
    for (final key in allKeys) {
      final valueA = _allValues[key];
      final valueB = other._allValues[key];
      final numA = valueA ?? 0.0;
      final numB = valueB ?? 0.0;
      result[key] = numA + (numB - numA) * t;
    }
    
    return FlyTextLineHeightToken(
      xs: result['xs']!,
      sm: result['sm']!,
      base: result['base']!,
      lg: result['lg']!,
      xl: result['xl']!,
      xl2: result['xl2']!,
      xl3: result['xl3']!,
      xl4: result['xl4']!,
      xl5: result['xl5']!,
      xl6: result['xl6']!,
      xl7: result['xl7']!,
      xl8: result['xl8']!,
      xl9: result['xl9']!,
      extras: Map.fromEntries(result.entries.where((e) => !['xs', 'sm', 'base', 'lg', 'xl', 'xl2', 'xl3', 'xl4', 'xl5', 'xl6', 'xl7', 'xl8', 'xl9'].contains(e.key))),
    );
  }

  /// Create default values
  static FlyTextLineHeightToken defaultTextLineHeight() {
    return const FlyTextLineHeightToken(
      xs: 1.3333333333333333,
      sm: 1.4285714285714286,
      base: 1.5,
      lg: 1.5555555555555556,
      xl: 1.4,
      xl2: 1.3333333333333333,
      xl3: 1.2,
      xl4: 1.1111111111111112,
      xl5: 1.0,
      xl6: 1.0,
      xl7: 1.0,
      xl8: 1.0,
      xl9: 1.0,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is FlyTextLineHeightToken && _allValues.toString() == other._allValues.toString();
  }

  @override
  int get hashCode => _allValues.hashCode;
}
