// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//
// Generated on: 2025-09-21T11:33:46.072961

/// Text shadow class with type-safe access to text shadow values
class FlyTextShadows {
  const FlyTextShadows({
    required this.2xs,
    required this.xs,
    required this.sm,
    required this.md,
    required this.lg,
    this.customTextShadows = const {},
  });

  final String 2xs;
  final String xs;
  final String sm;
  final String md;
  final String lg;
  final Map<String, String> customTextShadows;

  /// Get all values as a map
  Map<String, String> get values => {
    '2xs': 2xs,
    'xs': xs,
    'sm': sm,
    'md': md,
    'lg': lg,
    ...customTextShadows,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customTextShadows[key];

  /// Create a copy with updated values
  FlyTextShadows copyWith({
    String? 2xs,
    String? xs,
    String? sm,
    String? md,
    String? lg,
    Map<String, String>? customTextShadows,
  }) {
    return FlyTextShadows(
      2xs: 2xs ?? this.2xs,
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      customTextShadows: customTextShadows ?? this.customTextShadows,
    );
  }

  /// Default FlyTextShadows instance
  static const FlyTextShadows defaultTextShadows = FlyTextShadows(
    2xs: 'Shadow(color: Color.fromRGBO(0, 0, 0, 0.15), offset: Offset(0.0, 1.0), blurRadius: 0.0)',
    xs: 'Shadow(color: Color.fromRGBO(0, 0, 0, 0.2), offset: Offset(0.0, 1.0), blurRadius: 1.0)',
    sm: '[Shadow(color: Color.fromRGBO(0, 0, 0, 0.075), offset: Offset(0.0, 1.0), blurRadius: 0.0), Shadow(color: Color.fromRGBO(0, 0, 0, 0.075), offset: Offset(0.0, 1.0), blurRadius: 1.0), Shadow(color: Color.fromRGBO(0, 0, 0, 0.075), offset: Offset(0.0, 2.0), blurRadius: 2.0)]',
    md: '[Shadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 1.0), blurRadius: 1.0), Shadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 1.0), blurRadius: 2.0), Shadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 2.0), blurRadius: 4.0)]',
    lg: '[Shadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 1.0), blurRadius: 2.0), Shadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 3.0), blurRadius: 2.0), Shadow(color: Color.fromRGBO(0, 0, 0, 0.1), offset: Offset(0.0, 4.0), blurRadius: 8.0)]',
  );
}

/// Extension on FlyTextShadows to easily override specific values
extension FlyTextShadowsExtension on FlyTextShadows {
  /// Create a new FlyTextShadows instance with specific value overrides
  FlyTextShadows copyWith({
    String? 2xs,
    String? xs,
    String? sm,
    String? md,
    String? lg,
    Map<String, String>? customTextShadows,
  }) {
    return FlyTextShadows(
      2xs: 2xs ?? this.2xs,
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      customTextShadows: customTextShadows ?? this.customTextShadows,
    );
  }
}
