// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//
// Generated on: 2025-09-21T11:33:46.071309

/// Text line height class with type-safe access to line height values
class FlyTextLineHeights {
  const FlyTextLineHeights({
    required this.xs,
    required this.sm,
    required this.base,
    required this.lg,
    required this.xl,
    required this.xl2,
    required this.xl3,
    required this.xl4,
    required this.5xl,
    required this.6xl,
    required this.7xl,
    required this.8xl,
    required this.9xl,
    this.customTextLineHeights = const {},
  });

  final String xs;
  final String sm;
  final String base;
  final String lg;
  final String xl;
  final String xl2;
  final String xl3;
  final String xl4;
  final String 5xl;
  final String 6xl;
  final String 7xl;
  final String 8xl;
  final String 9xl;
  final Map<String, String> customTextLineHeights;

  /// Get all values as a map
  Map<String, String> get values => {
    'xs': xs,
    'sm': sm,
    'base': base,
    'lg': lg,
    'xl': xl,
    'xl2': xl2,
    'xl3': xl3,
    'xl4': xl4,
    '5xl': 5xl,
    '6xl': 6xl,
    '7xl': 7xl,
    '8xl': 8xl,
    '9xl': 9xl,
    ...customTextLineHeights,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customTextLineHeights[key];

  /// Create a copy with updated values
  FlyTextLineHeights copyWith({
    String? xs,
    String? sm,
    String? base,
    String? lg,
    String? xl,
    String? xl2,
    String? xl3,
    String? xl4,
    String? 5xl,
    String? 6xl,
    String? 7xl,
    String? 8xl,
    String? 9xl,
    Map<String, String>? customTextLineHeights,
  }) {
    return FlyTextLineHeights(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      base: base ?? this.base,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      xl4: xl4 ?? this.xl4,
      5xl: 5xl ?? this.5xl,
      6xl: 6xl ?? this.6xl,
      7xl: 7xl ?? this.7xl,
      8xl: 8xl ?? this.8xl,
      9xl: 9xl ?? this.9xl,
      customTextLineHeights: customTextLineHeights ?? this.customTextLineHeights,
    );
  }

  /// Default FlyTextLineHeights instance
  static const FlyTextLineHeights defaultTextLineHeights = FlyTextLineHeights(
    xs: '1.3333333333333333',
    sm: '1.4285714285714286',
    base: '1.5',
    lg: '1.5555555555555556',
    xl: '1.4',
    xl2: '1.3333333333333333',
    xl3: '1.2',
    xl4: '1.1111111111111112',
    5xl: '1',
    6xl: '1',
    7xl: '1',
    8xl: '1',
    9xl: '1',
  );
}

/// Extension on FlyTextLineHeights to easily override specific values
extension FlyTextLineHeightsExtension on FlyTextLineHeights {
  /// Create a new FlyTextLineHeights instance with specific value overrides
  FlyTextLineHeights copyWith({
    String? xs,
    String? sm,
    String? base,
    String? lg,
    String? xl,
    String? xl2,
    String? xl3,
    String? xl4,
    String? 5xl,
    String? 6xl,
    String? 7xl,
    String? 8xl,
    String? 9xl,
    Map<String, String>? customTextLineHeights,
  }) {
    return FlyTextLineHeights(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      base: base ?? this.base,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      xl4: xl4 ?? this.xl4,
      5xl: 5xl ?? this.5xl,
      6xl: 6xl ?? this.6xl,
      7xl: 7xl ?? this.7xl,
      8xl: 8xl ?? this.8xl,
      9xl: 9xl ?? this.9xl,
      customTextLineHeights: customTextLineHeights ?? this.customTextLineHeights,
    );
  }
}
