// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//
// Generated on: 2025-09-21T11:33:46.078499

/// Letter spacing class with type-safe access to letter spacing values
class FlyLetterSpacing {
  const FlyLetterSpacing({
    required this.tighter,
    required this.tight,
    required this.normal,
    required this.wide,
    required this.wider,
    required this.widest,
    this.customLetterSpacing = const {},
  });

  final String tighter;
  final String tight;
  final String normal;
  final String wide;
  final String wider;
  final String widest;
  final Map<String, String> customLetterSpacing;

  /// Get all values as a map
  Map<String, String> get values => {
    'tighter': tighter,
    'tight': tight,
    'normal': normal,
    'wide': wide,
    'wider': wider,
    'widest': widest,
    ...customLetterSpacing,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customLetterSpacing[key];

  /// Create a copy with updated values
  FlyLetterSpacing copyWith({
    String? tighter,
    String? tight,
    String? normal,
    String? wide,
    String? wider,
    String? widest,
    Map<String, String>? customLetterSpacing,
  }) {
    return FlyLetterSpacing(
      tighter: tighter ?? this.tighter,
      tight: tight ?? this.tight,
      normal: normal ?? this.normal,
      wide: wide ?? this.wide,
      wider: wider ?? this.wider,
      widest: widest ?? this.widest,
      customLetterSpacing: customLetterSpacing ?? this.customLetterSpacing,
    );
  }

  /// Default FlyLetterSpacing instance
  static const FlyLetterSpacing defaultLetterSpacing = FlyLetterSpacing(
    tighter: '-1',
    tight: '0',
    normal: '0',
    wide: '0',
    wider: '1',
    widest: '2',
  );
}

/// Extension on FlyLetterSpacing to easily override specific values
extension FlyLetterSpacingExtension on FlyLetterSpacing {
  /// Create a new FlyLetterSpacing instance with specific value overrides
  FlyLetterSpacing copyWith({
    String? tighter,
    String? tight,
    String? normal,
    String? wide,
    String? wider,
    String? widest,
    Map<String, String>? customLetterSpacing,
  }) {
    return FlyLetterSpacing(
      tighter: tighter ?? this.tighter,
      tight: tight ?? this.tight,
      normal: normal ?? this.normal,
      wide: wide ?? this.wide,
      wider: wider ?? this.wider,
      widest: widest ?? this.widest,
      customLetterSpacing: customLetterSpacing ?? this.customLetterSpacing,
    );
  }
}
