library tokens;

import 'package:flutter/material.dart';

// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind build runner
// To regenerate, run: dart run build_runner build
//
// Generated on: 2025-09-22T12:48:18.927470

/// Main FlyWind tokens class
class FlywindTokens {
  const FlywindTokens._();

  /// FlyColors instance
  static const FlyColors colors = FlyColors.defaultColors;

  /// FlySpacing instance
  static const FlySpacing spacing = FlySpacing.defaultSpacing;

  /// FlyRadius instance
  static  FlyRadius radius = FlyRadius.defaultRadius;

  /// FlyTextSize instance
  static  FlyTextSize text = FlyTextSize.defaultTextSize;

}

/// Color palette for the application
class FlyColors {
  const FlyColors({
    required this.primary,
    required this.secondary,
    required this.accent,
    required this.neutral,
    required this.success,
    required this.warning,
    required this.error,
    required this.info,
    required this.white,
    required this.black,
    this.customValues = const {},
  });

  final Color primary;
  final Color secondary;
  final Color accent;
  final Color neutral;
  final Color success;
  final Color warning;
  final Color error;
  final Color info;
  final Color white;
  final Color black;
  final Map<String, Color> customValues;

  /// Get all values as a map
  Map<String, Color> get values => {
    'primary': primary,
    'secondary': secondary,
    'accent': accent,
    'neutral': neutral,
    'success': success,
    'warning': warning,
    'error': error,
    'info': info,
    'white': white,
    'black': black,
    ...customValues,
  };

  /// Access values by key
  Color? operator [](String key) => values[key] ?? customValues[key];

  /// Create a copy with updated values
  FlyColors copyWith({
    Color? primary,
    Color? secondary,
    Color? accent,
    Color? neutral,
    Color? success,
    Color? warning,
    Color? error,
    Color? info,
    Color? white,
    Color? black,
    Map<String, Color>? customValues,
  }) {
    return FlyColors(
      primary: primary ?? this.primary,
      secondary: secondary ?? this.secondary,
      accent: accent ?? this.accent,
      neutral: neutral ?? this.neutral,
      success: success ?? this.success,
      warning: warning ?? this.warning,
      error: error ?? this.error,
      info: info ?? this.info,
      white: white ?? this.white,
      black: black ?? this.black,
      customValues: customValues ?? this.customValues,
    );
  }

  /// Default FlyColors instance
  static const FlyColors defaultColors = FlyColors(
    primary: Color(0xff3b82f6),
    secondary: Color(0xff10b981),
    accent: Color(0xfff59e0b),
    neutral: Color(0xff6b7280),
    success: Color(0xff10b981),
    warning: Color(0xfff59e0b),
    error: Color(0xffef4444),
    info: Color(0xff3b82f6),
    white: Color(0xffffffff),
    black: Color(0xff000000),
  );
}

/// Extension on FlyColors to easily override specific values
extension FlyColorsExtension on FlyColors {
  /// Create a new FlyColors instance with specific value overrides
  FlyColors copyWith({
    Color? primary,
    Color? secondary,
    Color? accent,
    Color? neutral,
    Color? success,
    Color? warning,
    Color? error,
    Color? info,
    Color? white,
    Color? black,
    Map<String, Color>? customValues,
  }) {
    return FlyColors(
      primary: primary ?? this.primary,
      secondary: secondary ?? this.secondary,
      accent: accent ?? this.accent,
      neutral: neutral ?? this.neutral,
      success: success ?? this.success,
      warning: warning ?? this.warning,
      error: error ?? this.error,
      info: info ?? this.info,
      white: white ?? this.white,
      black: black ?? this.black,
      customValues: customValues ?? this.customValues,
    );
  }
}


/// Spacing values for margins and padding
class FlySpacing {
  const FlySpacing({
    required this.s0,
    required this.s1,
    required this.s2,
    required this.s3,
    required this.s4,
    required this.s5,
    required this.s6,
    required this.s8,
    required this.s10,
    required this.s12,
    required this.s16,
    required this.s20,
    required this.s24,
    required this.s32,
    this.customValues = const {},
  });

  final double s0;
  final double s1;
  final double s2;
  final double s3;
  final double s4;
  final double s5;
  final double s6;
  final double s8;
  final double s10;
  final double s12;
  final double s16;
  final double s20;
  final double s24;
  final double s32;
  final Map<String, double> customValues;

  /// Get all values as a map
  Map<String, double> get values => {
    '0': s0,
    '1': s1,
    '2': s2,
    '3': s3,
    '4': s4,
    '5': s5,
    '6': s6,
    '8': s8,
    '10': s10,
    '12': s12,
    '16': s16,
    '20': s20,
    '24': s24,
    '32': s32,
  };

  /// Access values by index
  double? operator [](String index) => values[index];

  /// Create a copy with updated values
  FlySpacing copyWith({
    double? s0,
    double? s1,
    double? s2,
    double? s3,
    double? s4,
    double? s5,
    double? s6,
    double? s8,
    double? s10,
    double? s12,
    double? s16,
    double? s20,
    double? s24,
    double? s32,
    Map<String, double>? customValues,
  }) {
    return FlySpacing(
      s0: s0 ?? this.s0,
      s1: s1 ?? this.s1,
      s2: s2 ?? this.s2,
      s3: s3 ?? this.s3,
      s4: s4 ?? this.s4,
      s5: s5 ?? this.s5,
      s6: s6 ?? this.s6,
      s8: s8 ?? this.s8,
      s10: s10 ?? this.s10,
      s12: s12 ?? this.s12,
      s16: s16 ?? this.s16,
      s20: s20 ?? this.s20,
      s24: s24 ?? this.s24,
      s32: s32 ?? this.s32,
      customValues: customValues ?? this.customValues,
    );
  }

  /// Default FlySpacing instance
  static const FlySpacing defaultSpacing = FlySpacing(
    s0: 0.0,
    s1: 4.0,
    s2: 8.0,
    s3: 12.0,
    s4: 16.0,
    s5: 20.0,
    s6: 24.0,
    s8: 32.0,
    s10: 40.0,
    s12: 48.0,
    s16: 64.0,
    s20: 80.0,
    s24: 96.0,
    s32: 128.0,
  );
}

/// Extension on FlySpacing to easily override specific values
extension FlySpacingExtension on FlySpacing {
  /// Create a new FlySpacing instance with specific value overrides
  FlySpacing copyWith({
    double? s0,
    double? s1,
    double? s2,
    double? s3,
    double? s4,
    double? s5,
    double? s6,
    double? s8,
    double? s10,
    double? s12,
    double? s16,
    double? s20,
    double? s24,
    double? s32,
    Map<String, double>? customValues,
  }) {
    return FlySpacing(
      s0: s0 ?? this.s0,
      s1: s1 ?? this.s1,
      s2: s2 ?? this.s2,
      s3: s3 ?? this.s3,
      s4: s4 ?? this.s4,
      s5: s5 ?? this.s5,
      s6: s6 ?? this.s6,
      s8: s8 ?? this.s8,
      s10: s10 ?? this.s10,
      s12: s12 ?? this.s12,
      s16: s16 ?? this.s16,
      s20: s20 ?? this.s20,
      s24: s24 ?? this.s24,
      s32: s32 ?? this.s32,
      customValues: customValues ?? this.customValues,
    );
  }
}


/// Border radius values for rounded corners
class FlyRadius {
  const FlyRadius({
    required this.none,
    required this.sm,
    required this.defaultValue,
    required this.md,
    required this.lg,
    required this.xl,
    required this.xl2,
    required this.xl3,
    required this.full,
    this.customValues = const {},
  });

  final BorderRadius none;
  final BorderRadius sm;
  final BorderRadius defaultValue;
  final BorderRadius md;
  final BorderRadius lg;
  final BorderRadius xl;
  final BorderRadius xl2;
  final BorderRadius xl3;
  final BorderRadius full;
  final Map<String, BorderRadius> customValues;

  /// Get all values as a map
  Map<String, BorderRadius> get values => {
    'none': none,
    'sm': sm,
    'default': defaultValue,
    'md': md,
    'lg': lg,
    'xl': xl,
    '2xl': xl2,
    '3xl': xl3,
    'full': full,
    ...customValues,
  };

  /// Access values by key
  BorderRadius? operator [](String key) => values[key] ?? customValues[key];

  /// Create a copy with updated values
  FlyRadius copyWith({
    BorderRadius? none,
    BorderRadius? sm,
    BorderRadius? defaultValue,
    BorderRadius? md,
    BorderRadius? lg,
    BorderRadius? xl,
    BorderRadius? xl2,
    BorderRadius? xl3,
    BorderRadius? full,
    Map<String, BorderRadius>? customValues,
  }) {
    return FlyRadius(
      none: none ?? this.none,
      sm: sm ?? this.sm,
      defaultValue: defaultValue ?? this.defaultValue,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      full: full ?? this.full,
      customValues: customValues ?? this.customValues,
    );
  }

  /// Default FlyRadius instance
  static  FlyRadius defaultRadius = FlyRadius(
    none: BorderRadius.zero,
    sm: BorderRadius.circular(2.0),
    defaultValue: BorderRadius.circular(4.0),
    md: BorderRadius.circular(6.0),
    lg: BorderRadius.circular(8.0),
    xl: BorderRadius.circular(12.0),
    xl2: BorderRadius.circular(16.0),
    xl3: BorderRadius.circular(24.0),
    full: BorderRadius.circular(9999.0),
  );
}

/// Extension on FlyRadius to easily override specific values
extension FlyRadiusExtension on FlyRadius {
  /// Create a new FlyRadius instance with specific value overrides
  FlyRadius copyWith({
    BorderRadius? none,
    BorderRadius? sm,
    BorderRadius? defaultValue,
    BorderRadius? md,
    BorderRadius? lg,
    BorderRadius? xl,
    BorderRadius? xl2,
    BorderRadius? xl3,
    BorderRadius? full,
    Map<String, BorderRadius>? customValues,
  }) {
    return FlyRadius(
      none: none ?? this.none,
      sm: sm ?? this.sm,
      defaultValue: defaultValue ?? this.defaultValue,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      full: full ?? this.full,
      customValues: customValues ?? this.customValues,
    );
  }
}


/// Text styles for typography
class FlyTextSize {
  const FlyTextSize({
    required this.xs,
    required this.sm,
    required this.base,
    required this.lg,
    required this.xl,
    required this.xl2,
    required this.xl3,
    required this.xl4,
    this.customValues = const {},
  });

  final TextStyle xs;
  final TextStyle sm;
  final TextStyle base;
  final TextStyle lg;
  final TextStyle xl;
  final TextStyle xl2;
  final TextStyle xl3;
  final TextStyle xl4;
  final Map<String, TextStyle> customValues;

  /// Get all values as a map
  Map<String, TextStyle> get values => {
    'xs': xs,
    'sm': sm,
    'base': base,
    'lg': lg,
    'xl': xl,
    '2xl': xl2,
    '3xl': xl3,
    '4xl': xl4,
    ...customValues,
  };

  /// Access values by key
  TextStyle? operator [](String key) => values[key] ?? customValues[key];

  /// Create a copy with updated values
  FlyTextSize copyWith({
    TextStyle? xs,
    TextStyle? sm,
    TextStyle? base,
    TextStyle? lg,
    TextStyle? xl,
    TextStyle? xl2,
    TextStyle? xl3,
    TextStyle? xl4,
    Map<String, TextStyle>? customValues,
  }) {
    return FlyTextSize(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      base: base ?? this.base,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      xl4: xl4 ?? this.xl4,
      customValues: customValues ?? this.customValues,
    );
  }

  /// Default FlyTextSize instance
  static  FlyTextSize defaultTextSize = FlyTextSize(
    xs: TextStyle(fontSize: 12.0, height: 1.5),
    sm: TextStyle(fontSize: 14.0, height: 1.5),
    base: TextStyle(fontSize: 16.0, height: 1.5),
    lg: TextStyle(fontSize: 18.0, height: 1.5),
    xl: TextStyle(fontSize: 20.0, height: 1.5),
    xl2: TextStyle(fontSize: 24.0, height: 1.5),
    xl3: TextStyle(fontSize: 30.0, height: 1.5),
    xl4: TextStyle(fontSize: 36.0, height: 1.5),
  );
}

/// Extension on FlyTextSize to easily override specific values
extension FlyTextSizeExtension on FlyTextSize {
  /// Create a new FlyTextSize instance with specific value overrides
  FlyTextSize copyWith({
    TextStyle? xs,
    TextStyle? sm,
    TextStyle? base,
    TextStyle? lg,
    TextStyle? xl,
    TextStyle? xl2,
    TextStyle? xl3,
    TextStyle? xl4,
    Map<String, TextStyle>? customValues,
  }) {
    return FlyTextSize(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      base: base ?? this.base,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      xl4: xl4 ?? this.xl4,
      customValues: customValues ?? this.customValues,
    );
  }
}


