// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind Custom Token Generator
// To modify this file, edit fly-config.dart and run: dart tailwind/generate_custom_tokens.dart
//
// Generated on: 2025-09-21T13:29:20.691755

import '../tokens/spacing.dart';

/// Custom spacing tokens with direct property access
class CustomSpacing {
  const CustomSpacing._();

  /// Custom spacing: xs
  static const String xs = '2';
  /// Custom spacing: sm
  static const String sm = '4';
  /// Custom spacing: md
  static const String md = '8';
  /// Custom spacing: lg
  static const String lg = '16';
  /// Custom spacing: xl
  static const String xl = '32';
  /// Custom spacing: 2xl
  static const String xl2 = '48';

  /// All custom spacing values as a map
  static const Map<String, String> values = {
    'xs': xs,
    'sm': sm,
    'md': md,
    'lg': lg,
    'xl': xl,
    '2xl': xl2,
  };
}

/// Extension that adds custom spacing tokens to default FlySpacing
extension CustomSpacingExtension on FlySpacing {

  /// Custom spacing: xs
  String get xs => CustomSpacing.xs;
  /// Custom spacing: sm
  String get sm => CustomSpacing.sm;
  /// Custom spacing: md
  String get md => CustomSpacing.md;
  /// Custom spacing: lg
  String get lg => CustomSpacing.lg;
  /// Custom spacing: xl
  String get xl => CustomSpacing.xl;
  /// Custom spacing: 2xl
  String get xl2 => CustomSpacing.xl2;

  /// Get all spacing values (default + custom) as a map
  Map<String, String> get allSpacing => {
    ...this.values,
    ...CustomSpacing.values,
  };

  /// Access any spacing value by key (default or custom)
  String? operator [](String key) => allSpacing[key];
}
