// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind Custom Token Generator
// To modify this file, edit fly-config.dart and run: dart tailwind/generate_custom_tokens.dart
//
// Generated on: 2025-09-21T13:29:20.692594

export 'custom_colors.dart';
export 'custom_spacing.dart';
