// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//

/// Blur class with type-safe access to blur values
class FlyBlurs {
  const FlyBlurs({
    required this.xs,
    required this.sm,
    required this.md,
    required this.lg,
    required this.xl,
    required this.xl2,
    required this.xl3,
    this.customBlurs = const {},
  });

  final String xs;
  final String sm;
  final String md;
  final String lg;
  final String xl;
  final String xl2;
  final String xl3;
  final Map<String, String> customBlurs;

  /// Get all values as a map
  Map<String, String> get values => {
    'xs': xs,
    'sm': sm,
    'md': md,
    'lg': lg,
    'xl': xl,
    'xl2': xl2,
    'xl3': xl3,
    ...customBlurs,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customBlurs[key];

  /// Create a copy with updated values
  FlyBlurs copyWith({
    String? xs,
    String? sm,
    String? md,
    String? lg,
    String? xl,
    String? xl2,
    String? xl3,
    Map<String, String>? customBlurs,
  }) {
    return FlyBlurs(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      customBlurs: customBlurs ?? this.customBlurs,
    );
  }

  /// Default FlyBlurs instance
  static const FlyBlurs defaultBlurs = FlyBlurs(
    xs: '4',
    sm: '8',
    md: '12',
    lg: '16',
    xl: '24',
    xl2: '40',
    xl3: '64',
  );
}

/// Extension on FlyBlurs to easily override specific values
extension FlyBlursExtension on FlyBlurs {
  /// Create a new FlyBlurs instance with specific value overrides
  FlyBlurs copyWith({
    String? xs,
    String? sm,
    String? md,
    String? lg,
    String? xl,
    String? xl2,
    String? xl3,
    Map<String, String>? customBlurs,
  }) {
    return FlyBlurs(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      customBlurs: customBlurs ?? this.customBlurs,
    );
  }
}
