// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//

/// Inset shadow class with type-safe access to inset shadow values
class FlyInsetShadows {
  const FlyInsetShadows({
    required this.xs2,
    required this.xs,
    required this.sm,
    this.customInsetShadows = const {},
  });

  final String xs2;
  final String xs;
  final String sm;
  final Map<String, String> customInsetShadows;

  /// Get all values as a map
  Map<String, String> get values => {
    'xs2': xs2,
    'xs': xs,
    'sm': sm,
    ...customInsetShadows,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customInsetShadows[key];

  /// Create a copy with updated values
  FlyInsetShadows copyWith({
    String? xs2,
    String? xs,
    String? sm,
    Map<String, String>? customInsetShadows,
  }) {
    return FlyInsetShadows(
      xs2: xs2 ?? this.xs2,
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      customInsetShadows: customInsetShadows ?? this.customInsetShadows,
    );
  }

  /// Default FlyInsetShadows instance
  static const FlyInsetShadows defaultInsetShadows = FlyInsetShadows(
    xs2: 'InsetShadow(color: Colors.black.withOpacity(0.1), blurRadius: 4, offset: Offset(0, 2))',
    xs: 'InsetShadow(color: Colors.black.withOpacity(0.1), blurRadius: 4, offset: Offset(0, 2))',
    sm: 'InsetShadow(color: Colors.black.withOpacity(0.1), blurRadius: 4, offset: Offset(0, 2))',
  );
}

/// Extension on FlyInsetShadows to easily override specific values
extension FlyInsetShadowsExtension on FlyInsetShadows {
  /// Create a new FlyInsetShadows instance with specific value overrides
  FlyInsetShadows copyWith({
    String? xs2,
    String? xs,
    String? sm,
    Map<String, String>? customInsetShadows,
  }) {
    return FlyInsetShadows(
      xs2: xs2 ?? this.xs2,
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      customInsetShadows: customInsetShadows ?? this.customInsetShadows,
    );
  }
}
