// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//

/// Spacing class with type-safe access to spacing values
class FlySpacing {
  const FlySpacing({
    required this.base,
    this.customSpacing = const {},
  });

  final String base;
  final Map<String, String> customSpacing;

  /// Get all values as a map
  Map<String, String> get values => {
    'base': base,
    ...customSpacing,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customSpacing[key];

  /// Create a copy with updated values
  FlySpacing copyWith({
    String? base,
    Map<String, String>? customSpacing,
  }) {
    return FlySpacing(
      base: base ?? this.base,
      customSpacing: customSpacing ?? this.customSpacing,
    );
  }

  /// Default FlySpacing instance
  static const FlySpacing defaultSpacing = FlySpacing(
    base: '4',
  );
}

/// Extension on FlySpacing to easily override specific values
extension FlySpacingExtension on FlySpacing {
  /// Create a new FlySpacing instance with specific value overrides
  FlySpacing copyWith({
    String? base,
    Map<String, String>? customSpacing,
  }) {
    return FlySpacing(
      base: base ?? this.base,
      customSpacing: customSpacing ?? this.customSpacing,
    );
  }
}
