// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//

/// Text size class with type-safe access to text size values
class FlyTextSizes {
  const FlyTextSizes({
    required this.xs,
    required this.sm,
    required this.base,
    required this.lg,
    required this.xl,
    required this.xl2,
    required this.xl3,
    required this.xl4,
    required this.xl5,
    required this.xl6,
    required this.xl7,
    required this.xl8,
    required this.xl9,
    this.customTextSizes = const {},
  });

  final String xs;
  final String sm;
  final String base;
  final String lg;
  final String xl;
  final String xl2;
  final String xl3;
  final String xl4;
  final String xl5;
  final String xl6;
  final String xl7;
  final String xl8;
  final String xl9;
  final Map<String, String> customTextSizes;

  /// Get all values as a map
  Map<String, String> get values => {
    'xs': xs,
    'sm': sm,
    'base': base,
    'lg': lg,
    'xl': xl,
    'xl2': xl2,
    'xl3': xl3,
    'xl4': xl4,
    'xl5': xl5,
    'xl6': xl6,
    'xl7': xl7,
    'xl8': xl8,
    'xl9': xl9,
    ...customTextSizes,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customTextSizes[key];

  /// Create a copy with updated values
  FlyTextSizes copyWith({
    String? xs,
    String? sm,
    String? base,
    String? lg,
    String? xl,
    String? xl2,
    String? xl3,
    String? xl4,
    String? xl5,
    String? xl6,
    String? xl7,
    String? xl8,
    String? xl9,
    Map<String, String>? customTextSizes,
  }) {
    return FlyTextSizes(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      base: base ?? this.base,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      xl4: xl4 ?? this.xl4,
      xl5: xl5 ?? this.xl5,
      xl6: xl6 ?? this.xl6,
      xl7: xl7 ?? this.xl7,
      xl8: xl8 ?? this.xl8,
      xl9: xl9 ?? this.xl9,
      customTextSizes: customTextSizes ?? this.customTextSizes,
    );
  }

  /// Default FlyTextSizes instance
  static const FlyTextSizes defaultTextSizes = FlyTextSizes(
    xs: '12',
    sm: '14',
    base: '16',
    lg: '18',
    xl: '20',
    xl2: '24',
    xl3: '30',
    xl4: '36',
    xl5: '48',
    xl6: '60',
    xl7: '72',
    xl8: '96',
    xl9: '128',
  );
}

/// Extension on FlyTextSizes to easily override specific values
extension FlyTextSizesExtension on FlyTextSizes {
  /// Create a new FlyTextSizes instance with specific value overrides
  FlyTextSizes copyWith({
    String? xs,
    String? sm,
    String? base,
    String? lg,
    String? xl,
    String? xl2,
    String? xl3,
    String? xl4,
    String? xl5,
    String? xl6,
    String? xl7,
    String? xl8,
    String? xl9,
    Map<String, String>? customTextSizes,
  }) {
    return FlyTextSizes(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      base: base ?? this.base,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      xl4: xl4 ?? this.xl4,
      xl5: xl5 ?? this.xl5,
      xl6: xl6 ?? this.xl6,
      xl7: xl7 ?? this.xl7,
      xl8: xl8 ?? this.xl8,
      xl9: xl9 ?? this.xl9,
      customTextSizes: customTextSizes ?? this.customTextSizes,
    );
  }
}
