// GENERATED FILE - DO NOT EDIT MANUALLY
// This file was generated by FlyWind CLI
// To modify this file, edit the JSON configuration in tokens/ directory and run: dart tool/generate_tokens.dart
//

/// Text line height class with type-safe access to line height values
class FlyTextLineHeights {
  const FlyTextLineHeights({
    required this.xs,
    required this.sm,
    required this.base,
    required this.lg,
    required this.xl,
    required this.xl2,
    required this.xl3,
    required this.xl4,
    required this.xl5,
    required this.xl6,
    required this.xl7,
    required this.xl8,
    required this.xl9,
    this.customTextLineHeights = const {},
  });

  final String xs;
  final String sm;
  final String base;
  final String lg;
  final String xl;
  final String xl2;
  final String xl3;
  final String xl4;
  final String xl5;
  final String xl6;
  final String xl7;
  final String xl8;
  final String xl9;
  final Map<String, String> customTextLineHeights;

  /// Get all values as a map
  Map<String, String> get values => {
    'xs': xs,
    'sm': sm,
    'base': base,
    'lg': lg,
    'xl': xl,
    'xl2': xl2,
    'xl3': xl3,
    'xl4': xl4,
    'xl5': xl5,
    'xl6': xl6,
    'xl7': xl7,
    'xl8': xl8,
    'xl9': xl9,
    ...customTextLineHeights,
  };

  /// Access values by key
  String? operator [](String key) => values[key] ?? customTextLineHeights[key];

  /// Create a copy with updated values
  FlyTextLineHeights copyWith({
    String? xs,
    String? sm,
    String? base,
    String? lg,
    String? xl,
    String? xl2,
    String? xl3,
    String? xl4,
    String? xl5,
    String? xl6,
    String? xl7,
    String? xl8,
    String? xl9,
    Map<String, String>? customTextLineHeights,
  }) {
    return FlyTextLineHeights(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      base: base ?? this.base,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      xl4: xl4 ?? this.xl4,
      xl5: xl5 ?? this.xl5,
      xl6: xl6 ?? this.xl6,
      xl7: xl7 ?? this.xl7,
      xl8: xl8 ?? this.xl8,
      xl9: xl9 ?? this.xl9,
      customTextLineHeights: customTextLineHeights ?? this.customTextLineHeights,
    );
  }

  /// Default FlyTextLineHeights instance
  static const FlyTextLineHeights defaultTextLineHeights = FlyTextLineHeights(
    xs: '1.3333333333333333',
    sm: '1.4285714285714286',
    base: '1.5',
    lg: '1.5555555555555556',
    xl: '1.4',
    xl2: '1.3333333333333333',
    xl3: '1.2',
    xl4: '1.1111111111111112',
    xl5: '1',
    xl6: '1',
    xl7: '1',
    xl8: '1',
    xl9: '1',
  );
}

/// Extension on FlyTextLineHeights to easily override specific values
extension FlyTextLineHeightsExtension on FlyTextLineHeights {
  /// Create a new FlyTextLineHeights instance with specific value overrides
  FlyTextLineHeights copyWith({
    String? xs,
    String? sm,
    String? base,
    String? lg,
    String? xl,
    String? xl2,
    String? xl3,
    String? xl4,
    String? xl5,
    String? xl6,
    String? xl7,
    String? xl8,
    String? xl9,
    Map<String, String>? customTextLineHeights,
  }) {
    return FlyTextLineHeights(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      base: base ?? this.base,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      xl2: xl2 ?? this.xl2,
      xl3: xl3 ?? this.xl3,
      xl4: xl4 ?? this.xl4,
      xl5: xl5 ?? this.xl5,
      xl6: xl6 ?? this.xl6,
      xl7: xl7 ?? this.xl7,
      xl8: xl8 ?? this.xl8,
      xl9: xl9 ?? this.xl9,
      customTextLineHeights: customTextLineHeights ?? this.customTextLineHeights,
    );
  }
}
